prototype(2)
im-d-team/Dev-Docs pull request #163
Opened 2020-08-03 13:30 UTC by dididy

[Javascript/prototype(2).md](https://github.com/im-d-team/Dev-Docs/blob/20200803/dididy/Javascript/prototype(2).md)

2020-08-24 03:49 UTC, SeonHyungJo requested changes
몇 가지 궁금한 사항과 리뷰를 남겼습니다. 확인부탁드립니다. 공부에 열정적인 모습이 보기 좋습니다. 👍

2020-08-24 03:49 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +객체 내에 프로퍼티가 존재하지 않으면 [[Prototype]] 을 따라가 프로퍼티가 존재하는지 탐색하게 된다.
어떤 경우에 프로퍼티가 존재하지 않는지 확인을 하는 걸까요?

2020-08-24 03:49 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +위 코드는 프로토타입 체이닝의 예시이다. toString 메서드는 object에 존재하지 않지만, 메소드로서 호출할 수 있다.
```suggestion
위 코드는 프로토타입 체이닝의 예시이다. `toString()` 메서드는 object에 존재하지 않지만, 메소드로서 호출할 수 있다.
```

메소드 같은 것은 code로 감싸주는게 더 눈에 잘 띄어보입니다.

2020-08-24 03:49 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +Object는 자바스크립트에서 기본적으로 제공하는 함수이다. 이것을 토대로 알 수 있는 건 객체는 언제나 함수로 생성된다는 것이다. Object 외에도 Function, Array 또한 함수로 정의되어 있다. 일반 객체가 [[Prototype]] 만 가지고 있는 것과 달리 함수는 프로토타입 프로퍼티도 가지고 있다.
Object라는게 위에서 언급해주신 코드인가요? `new Object()`

2020-08-24 03:49 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
Constructor 자격이 부여된다고 해주셨는데 제가 임의로 줄 수도 있는 건가요?

2020-08-24 03:49 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +Object.create(proto[, dscriptions])는 아래에서 설명할 프로토타입 메서드의 한 종류로서 [[Prototype]] 이 proto를 참조하는 빈 객체를 만든다. 이렇게 만들어진 other는 something이랑 [[Prototype]] 이 링크된다. other 내부에 value 프로퍼티가 없지만 연결된 something에서 해당 프
dscriptions에 대한 간단한 설명이 있어도 좋아보입니다. 실제로 Vallina로 사용하게 되면 설정하는 경우가 있어서요

2020-08-25 17:12 UTC, dididy commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
<img width="289" alt="Screen Shot 2020-08-26 at 2 01 28 AM" src="https://user-images.githubusercontent.com/16266103/91205167-14234380-e740-11ea-96db-0e7bdb233b7a.png">
해보니 가능합니다! 이부분을 문서에 녹여낼까요?

2020-08-25 17:12 UTC, dididy commented on Javascript/prototype(2).md
> +Object.create(proto[, dscriptions])는 아래에서 설명할 프로토타입 메서드의 한 종류로서 [[Prototype]] 이 proto를 참조하는 빈 객체를 만든다. 이렇게 만들어진 other는 something이랑 [[Prototype]] 이 링크된다. other 내부에 value 프로퍼티가 없지만 연결된 something에서 해당 프
네넵 해당 옵션은 현재 [propertiesObject](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/create)로 변경된 것 같습니다. 저번에 immutable 하게 할건지 설정할 때 사용했다고 들었는데 추가적인 상황도 생각해서 간단한 설명을 추가해 보도록 하겠습니다!

2020-08-25 17:12 UTC, dididy commented on Javascript/prototype(2).md
> +- [Object.create(proto[, descriptors])](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/create) – `[[Prototype]]`이 `proto`를 참조하는 빈 객체를 만들고 이때 프로퍼티 설명자를 추가로 넘길 수 있
```suggestion
- [Object.create(proto[, propertiesObject])](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/create) – `[[Prototype]]`이 `proto`를 참조하는 빈 객체를 만들고 이때 프로퍼티 설명자를 추가로 넘길 수 있다.
```
여기도 이렇게 수정해야겠네요.

2020-08-25 17:12 UTC, dididy commented on Javascript/prototype(2).md
> +사실 `__proto__`는 표준이 아니지만 모든 브라우저에 구현되어 있기 때문에 사실상 표준(de-facto standard)이 된 케이스이다.
이부분도 `모든 브라우저`라는 표현보다는 `대부분의 브라우저` 정도로 수정하겠습니다.

2020-08-25 17:12 UTC, dididy commented on Javascript/prototype(2).md
> +- [Object.create(proto[, descriptors])](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/create) – `[[Prototype]]`이 `proto`를 참조하는 빈 객체를 만들고 이때 프로퍼티 설명자를 추가로 넘길 수 있
이 부분에 arrow function에서는 동작하지 않는다는 것도 추가해보도록 하겠습니다!

2020-08-25 17:14 UTC, dididy commented on Javascript/prototype(2).md
> +객체 내에 프로퍼티가 존재하지 않으면 [[Prototype]] 을 따라가 프로퍼티가 존재하는지 탐색하게 된다.
작성 당시 `현재 객체에 특정 프로퍼티에 접근할 경우`의 케이스를 생각했습니다! 이부분을 앞에 추가하면 될까요?

2020-08-25 17:15 UTC, dididy commented on Javascript/prototype(2).md
> +위 코드는 프로토타입 체이닝의 예시이다. toString 메서드는 object에 존재하지 않지만, 메소드로서 호출할 수 있다.
반영하겠습니다. 감사합니다!

2020-08-25 17:15 UTC, dididy commented on Javascript/prototype(2).md
> +Object는 자바스크립트에서 기본적으로 제공하는 함수이다. 이것을 토대로 알 수 있는 건 객체는 언제나 함수로 생성된다는 것이다. Object 외에도 Function, Array 또한 함수로 정의되어 있다. 일반 객체가 [[Prototype]] 만 가지고 있는 것과 달리 함수는 프로토타입 프로퍼티도 가지고 있다.
네 맞습니다. 지금 보니 `생성자 함수` 정도로 변경해도 좋을 것 같네요.

2020-08-25 17:15 UTC, dididy commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
<img width="289" alt="Screen Shot 2020-08-26 at 2 01 28 AM" src="https://user-images.githubusercontent.com/16266103/91205167-14234380-e740-11ea-96db-0e7bdb233b7a.png">
해보니 가능합니다! 이부분을 문서에 녹여낼까요?

2020-08-25 17:16 UTC, dididy commented on Javascript/prototype(2).md
> +Object.create(proto[, dscriptions])는 아래에서 설명할 프로토타입 메서드의 한 종류로서 [[Prototype]] 이 proto를 참조하는 빈 객체를 만든다. 이렇게 만들어진 other는 something이랑 [[Prototype]] 이 링크된다. other 내부에 value 프로퍼티가 없지만 연결된 something에서 해당 프
네넵 해당 옵션은 현재 [propertiesObject](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/create)로 변경된 것 같습니다. 저번에 immutable 하게 할건지 설정할 때 사용했다고 들었는데 추가적인 상황도 생각해서 간단한 설명을 추가해 보도록 하겠습니다!

2020-09-05 17:08 UTC, EUNJIHA reviewed
프로토타입을 세밀하게 설명해주신 점이 좋은 거 같아요. 몇가지 리뷰 확인 부탁드립니다!

2020-09-05 17:08 UTC, EUNJIHA commented on Javascript/prototype(2).md
> +## 프로토타입 링크(`[[Prototype]]`)
[[Prototype]] 이게 그림상에서 무엇을 의미하는지 궁금합니다. 저는 프로토타입 링크( __proto__) 이것과 같은 의미라고 생각했는데 밑 부분의 설명에서는 

 `__proto__`는 객체의 프로퍼티가 아니라 Object.prototype의 접근자 프로퍼티이다. 그렇기 때문에 사실상 `__proto__`는 [[Prototype]] 에 접근하기 위한 방법일 뿐 [[Prototype]] 그 자체는 아니다.

이라고 나와있어서 조금 헷갈리는 거 같습니다

2020-09-07 16:36 UTC, dididy commented on Javascript/prototype(2).md
> +다음과 같이 생성자 함수를 이용해 객체를 생성할 수 있다.
네네 감사합니다! 반영하도록 하겠습니다!

2020-09-07 19:15 UTC, dididy commented on Javascript/prototype(2).md
> +## 프로토타입 링크(`[[Prototype]]`)
[[Prototype]]과 프로토타입 링크(`__proto__`)는 같은 것을 의미하는게 맞지만 프로토타입 링크(`__proto__`)는 표준은 아닙니다. 스크린샷의 경우 프로토타입 링크(`__proto__`)가  [[Prototoype]]을 의미하는거라고 보시면 될 것 같고 이부분에 대해 더 잘 이해할 수 있도록 추가적인 설명을 덧붙여보겠습니다.

2020-09-09 01:16 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
@dididy 하나 더 궁금한게 그렇다면 저렇게 임의로 constructor를 변경하고 new를 사용해서 인스턴스를 만들게 되면 그 인스턴스의 객체는 누구를 따르나요?

2020-09-09 05:04 UTC, EUNJIHA approved these changes
승인합니다 :)

2020-09-09 23:50 UTC, Dae-Hwa approved these changes
고생하셨습니다. 승인합니다.

2020-09-22 04:24 UTC, JegalEun approved these changes
고생하셨습니다~ 승인하겠습니다!

2020-10-13 10:43 UTC, dididy commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
@SeonHyungJo 늦은 답변 죄송합니다. 제가 놓쳤네요 ㅠㅠ 

![Screen Shot 2020-10-13 at 7 41 13 PM](https://user-images.githubusercontent.com/16266103/95850625-198a2b00-0d8c-11eb-9c2e-d222d73cd21f.png)
new를 이용해 만들더라도 임의로 변경해놓은 constructor에 따라가게 되는군요. 그리고 더 확인해보고 싶어서 consturctor를 변경하기 전에 new로 인스턴스를 하나 만들어놓고 constructor 변경한 뒤 어떻게 되나 확인해봤는데 해당 인스턴스의 객체도 변경한 constructor를 따라감을 확인하였습니다!

2020-10-26 03:43 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
![image](https://user-images.githubusercontent.com/24274424/97131913-b84d5900-1788-11eb-8810-46701bb6d7ca.png)

`new aa();`로 생성된 aa_nn의 생성자가 bb로 바뀐건 잘 이해했습니다. 그렇다면 `aa_nn`을 찍으면 왜 bb는 안나오는 걸까요?

2020-10-28 14:26 UTC, dididy commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
@SeonHyungJo 개념적으로 제가 부족한 부분이 있는 것 같네요. 좀 더 공부해보도록 하겠습니다!

2020-10-30 07:09 UTC, SeonHyungJo commented on Javascript/prototype(2).md
> +생성자 함수 키워드인 new를 통해 객체를 만들기 위해선 Constructor 자격이 필요하다. 함수를 정의하게 되면 Constructor 자격이 부여되어 new를 사용할 수 있다.
@dididy 아 그런 의미가 아니였는데 죄송합니다. 단순히 저도 궁금해서 질문한 거 였습니다.

2020-10-30 07:10 UTC, SeonHyungJo approved these changes
모르는 부분은 같이 다음에 알아가면 될 듯 합니다. 수고하셨습니다.

2020-10-30 07:10 UTC, merged