FOUC
im-d-team/Dev-Docs pull request #165
Opened 2020-08-09 04:58 UTC by BKJang

2020-08-24 03:53 UTC, SeonHyungJo requested changes
오랜만에 보는 좋은 내용이네요. 리뷰 남겼습니다.

2020-08-24 03:53 UTC, SeonHyungJo commented on Browser/FOUC.md
> +`FOUC`의 발생은 최근에는 대부분 `IE`에서 발생하기 때문에 `IE`에 대해서만 분기 처리를 한 후 `FOUC`에 대한 처리를 하는 것도 좋으 방법이 될 수 있다.
```suggestion
`FOUC`의 발생은 최근에는 대부분 `IE`에서 발생하기 때문에 `IE`에 대해서만 분기 처리를 한 후 `FOUC`에 대한 처리를 하는 것도 좋은 방법이 될 수 있다.
```

2020-09-17 11:18 UTC, Dae-Hwa requested changes

2020-09-17 11:18 UTC, Dae-Hwa commented on Browser/FOUC.md
> +위 소스에 대해 간단히 설명하면 자바스크립트와 CSS 스타일이 모두 로딩되었을 경우, `fouc` ID를 가진 컴포넌트를 렌더링시켜준다.
```suggestion
위 소스에 대해 간단히 설명하면 자바스크립트와 CSS 스타일이 모두 로딩되었을 경우, `FOUC` ID를 가진 컴포넌트를 렌더링시켜준다.
```

2020-09-17 11:18 UTC, Dae-Hwa commented on Browser/FOUC.md
> +위 소스에 대해 간단히 설명하면 자바스크립트와 CSS 스타일이 모두 로딩되었을 경우, `fouc` ID를 가진 컴포넌트를 렌더링시켜준다.
여기만 소문자로 쓰였네요 😀

2020-09-22 08:23 UTC, JegalEun approved these changes
새로운 개념 알고갑니다~ 승인하겠습니다.

2020-10-19 00:54 UTC, BKJang commented on Browser/FOUC.md
> +위 소스에 대해 간단히 설명하면 자바스크립트와 CSS 스타일이 모두 로딩되었을 경우, `fouc` ID를 가진 컴포넌트를 렌더링시켜준다.
@Dae-Hwa 
```html
<div id="fouc">
   FOUC 발생 지점
 </div>
```

해당 엘리먼트의 ID 값이 fouc라는 의미입니다 :)

2020-10-28 05:12 UTC, Dae-Hwa approved these changes

2020-10-28 14:36 UTC, dididy approved these changes

2020-11-01 09:48 UTC, BKJang commented on Browser/FOUC.md
> +`FOUC`의 발생은 최근에는 대부분 `IE`에서 발생하기 때문에 `IE`에 대해서만 분기 처리를 한 후 `FOUC`에 대한 처리를 하는 것도 좋으 방법이 될 수 있다.
@SeonHyungJo 수정했습니다

2020-11-03 07:16 UTC, SeonHyungJo approved these changes
승인합니다.

2020-11-03 07:16 UTC, merged