String,StringBuilder,StringBuffer
im-d-team/Dev-Docs pull request #168
Opened 2020-08-23 05:00 UTC by JegalEun

[Java/String,StringBuilder, StringBuffer차이.md](https://github.com/im-d-team/Dev-Docs/blob/20200823/JegalEun/Java/String,StringBuilder,%20StringBuffer%EC%B0%A8%EC%9D%B4.md)

2020-09-07 11:37 UTC, jigi-kim approved these changes

2020-09-22 02:59 UTC, EUNJIHA reviewed
리뷰 확인 부탁드립니다. 3가지에 대해서 명확하게 비교 분석 해주신 점이 좋았어요 :)

2020-09-22 02:59 UTC, EUNJIHA commented on Java/String,StringBuilder, StringBuffer차이.md
> +단일 스레드 환경이라면 `StringBuilder`를 사용하는 것이 좋다. 무조건 단일 스레드 환경에서는 `StringBuffer`를 사용해라!는 아니지만 동기화 관련 처리로 인해 `StringBilder`에 비해 성능이 좋지 않다.
```suggestion
단일 스레드 환경이라면 `StringBuilder`를 사용하는 것이 좋다. 무조건 단일 스레드 환경에서는 `StringBuilder`를 사용해라!는 아니지만 동기화 관련 처리를 하지 않기 때문에 `StringBuffer`에 비해 성능이 좋다.
```

원래 의도하셨던 바가 이게 맞을까요?

2020-09-22 08:41 UTC, JegalEun commented on Java/String,StringBuilder, StringBuffer차이.md
> +단일 스레드 환경이라면 `StringBuilder`를 사용하는 것이 좋다. 무조건 단일 스레드 환경에서는 `StringBuffer`를 사용해라!는 아니지만 동기화 관련 처리로 인해 `StringBilder`에 비해 성능이 좋지 않다.
`무조건 단일 스레드 환경에서는 `StringBuilder`를 사용해라!는 아니지만 동기화 관련 처리를 하지 않기 때문에 `StringBuffer`에 비해 성능이 좋지 않다.`가 의도한 바였습니다!
당시 발표할 때 @Dae-Hwa 님께서 단일 스레드 환경에서는 StringBuilder를 사용하는 것이 좋다는 의견을 내주셔서 문서 수정을 하였습니다~

2020-09-22 13:59 UTC, EUNJIHA approved these changes
미리 approve 할게요 :) 리뷰 확인 부탁드립니다!

2020-09-22 13:59 UTC, EUNJIHA commented on Java/String,StringBuilder, StringBuffer차이.md
> +하지만 StringBuilder가 동기화를 고려하지 않기 때문에 단일 스레드 환경에서 StringBuffer에 비해 연산처리가 빠른 장점이 있다.
```suggestion
StringBuilder가 동기화를 고려하지 않기 때문에 단일 스레드 환경에서 StringBuffer에 비해 연산처리가 빠른 장점이 있다.
```
앞서 말씀해주신 내용과 동일한 맥락으로 보여서 하지만을 빼도 될거 같아요! 내용은 깔끔하게 잘 정리 된거 같습니다 :)

2020-10-26 05:48 UTC, JegalEun commented on Java/String,StringBuilder, StringBuffer차이.md
> +하지만 StringBuilder가 동기화를 고려하지 않기 때문에 단일 스레드 환경에서 StringBuffer에 비해 연산처리가 빠른 장점이 있다.
수정했습니다~

2020-10-30 07:28 UTC, SeonHyungJo requested changes
간단하게 리뷰 남겼습니다. 확인 부탁드립니다.

2020-10-30 07:28 UTC, SeonHyungJo commented on Java/String,StringBuilder, StringBuffer차이.md
> +먼저 `String`과 다른 클래스(StringBuffer, StringBuilder)의 차이점은 String은 **immutable**(불변), `StringBuffer`는 **mutable**(변함)에 있다.
```suggestion
먼저 `String`과 다른 클래스(StringBuffer, StringBuilder)의 차이점은 String은 **immutable**(불변), `StringBuffer`, `StringBuilder`는 **mutable**(변함)에 있다.
```

2020-11-01 09:49 UTC, BKJang approved these changes
오랜만에 보네요 승인합니다
고생하셨어요 👍

2020-11-03 06:47 UTC, JegalEun commented on Java/String,StringBuilder, StringBuffer차이.md
> +먼저 `String`과 다른 클래스(StringBuffer, StringBuilder)의 차이점은 String은 **immutable**(불변), `StringBuffer`는 **mutable**(변함)에 있다.
수정하였습니다😁

2020-11-03 07:16 UTC, SeonHyungJo approved these changes
수고하셨습니다. 승인합니다. 👍

2020-11-03 07:16 UTC, merged