Types of Databases
im-d-team/Dev-Docs pull request #173
Opened 2020-08-30 05:45 UTC by EUNJIHA

2020-09-07 11:52 UTC, jigi-kim requested changes
문서 내용에 대한 질문 및 수정/확인 요청을 남깁니다.

2020-09-07 11:52 UTC, jigi-kim commented on Android/application fundamentals.md
> +# 안드로이드 (Android)
리뷰를 하려고 열심히 읽다보니 어쩐지 내용이 너무 익숙하던데...

[application fundamental](https://github.com/im-d-team/Dev-Docs/pull/166) 글이 같이 commit 된 것 같네요 ㅎㅎ 본 pull request에서는 `application fundamentals.md` 추가사항은 제외하는게 좋겠습니다.

2020-09-07 11:52 UTC, jigi-kim commented on Database/Types of Databases.md
> +NoSQL을 구체적으로 이해하기 위해 먼저 RDB가 무엇인지 살펴보자. RDB는 1970년대 탄생 이후 지금까지 수십년간 가장 많이 사용된 DB 모델이다. RDB는 데이터를 정형화된 구조(Strict Schema)에 따라 테이블(Table)에 저장하는 형식이다. 각 테이블은 관계(Relations)를 갖고 있는데 이는 RDB가 데이터의 중복을 방지하고 [
```suggestion
NoSQL을 구체적으로 이해하기 위해 먼저 RDB가 무엇인지 살펴보자. RDB는 1970년대 탄생 이후 지금까지 수십년간 가장 많이 사용된 DB 모델이다. RDB는 데이터를 정형화된 구조(Strict Schema)에 따라 테이블(Table)에 저장하는 형식이다. 각 테이블은 관계(Relations)를 갖고 있는데 이는 RDB가 데이터의 중복을 방지하고 [참조 무결성](https://ko.wikipedia.org/wiki/%EC%B0%B8%EC%A1%B0_%EB%AC%B4%EA%B2%B0%EC%84%B1)이 보장되도록 한다. 더불어 [ACID 속성](https://ko.wikipedia.org/wiki/ACID)을 갖고 있다. 예시로는 MySQL, PostgreSQL, MariaDB, Oracle SQL, MSSQL 등이 있다.
```

2020-09-07 11:52 UTC, jigi-kim commented on Database/Types of Databases.md
> +- 일반적으로 키-값 데이터베이스는 관계형 데이터베이스에 비하여 페이지당 제공하는 [오버헤드](https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B2%84%ED%97%A4%EB%93%9C)가 적다. (데이터 양이 많아져도 일관적인 성능을 갖는다.)
윗줄의 `(읽고 쓰는 속도가 빠르다.)`와 아랫줄의 설명이 상통하는 개념으로 보이는데 제가 이해한게 맞나요?

2020-09-09 05:06 UTC, EUNJIHA commented on Database/Types of Databases.md
> +- 일반적으로 키-값 데이터베이스는 관계형 데이터베이스에 비하여 페이지당 제공하는 [오버헤드](https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B2%84%ED%97%A4%EB%93%9C)가 적다. (데이터 양이 많아져도 일관적인 성능을 갖는다.)
네 상통하는 개념이 맞습니다!

2020-09-09 05:09 UTC, EUNJIHA commented on Android/application fundamentals.md
> +# 안드로이드 (Android)
반영했습니다 : ) 같이 올라갈 뻔 했네요!

2020-09-11 18:13 UTC, jigi-kim commented on Database/Types of Databases.md
> +- 일반적으로 키-값 데이터베이스는 관계형 데이터베이스에 비하여 페이지당 제공하는 [오버헤드](https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B2%84%ED%97%A4%EB%93%9C)가 적다. (데이터 양이 많아져도 일관적인 성능을 갖는다.)
@EUNJIHA 그렇다면 윗줄의 설명보다는 아랫쪽의 내용에 더 부합하는 설명 같네요.

괄호 안의 내용을 아래로 옮기거나, 혹은 아랫줄의 `(데이터 양이 많아져도 일관적인 성능을 갖는다.)`가 이미 유사한 설명을 보이는 것 같으니 제거해도 무방할 것 같습니다.

2020-09-15 04:31 UTC, EUNJIHA commented on Database/Types of Databases.md
> +- 일반적으로 키-값 데이터베이스는 관계형 데이터베이스에 비하여 페이지당 제공하는 [오버헤드](https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B2%84%ED%97%A4%EB%93%9C)가 적다. (데이터 양이 많아져도 일관적인 성능을 갖는다.)
당시에 쓰면서도 내용 중복이 아닌가 생각했었는데 잘 짚어주신거 같아요! 수정하겠습니다 :)

2020-09-15 04:33 UTC, EUNJIHA commented on Database/Types of Databases.md
> +- 일반적으로 키-값 데이터베이스는 관계형 데이터베이스에 비하여 페이지당 제공하는 [오버헤드](https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B2%84%ED%97%A4%EB%93%9C)가 적다. (데이터 양이 많아져도 일관적인 성능을 갖는다.)
당시에 쓰면서도 내용 중복이 아닌가 생각했었는데 잘 짚어주신거 같아요. 수정하겠습니다 :)

2020-09-21 13:39 UTC, jigi-kim approved these changes

2020-10-28 05:57 UTC, Dae-Hwa commented
요즘 DB쪽 계속 보고 있다 하셨는데 ACID와 BASE 비교를 해보는 것도 좋을 것 같네요 잘 읽었습니다.

2020-10-28 05:58 UTC, Dae-Hwa approved these changes

2020-10-30 07:49 UTC, SeonHyungJo reviewed
잘 읽었습니다. 👍  간단한 리뷰 남겼습니다. 확인 부탁드려요

2020-10-30 07:49 UTC, SeonHyungJo commented on Database/Types of Databases.md
> +|ACID 속성|	관계형 데이터베이스는 원자가, 일관성, 격리성 및 지속성(ACID, atomicity, consistency, isolation, and durability)의 속성을 제공합니다 1) 원자가는 완벽하게 실행하거나 혹은 전혀 실행하지 않는 트랜잭션을 필요로 합니다. 2) 일관성은 트랜잭션이 커밋되면 데이터가 데이터베이스 스키마를 준수하도록
```suggestion
|ACID 속성|	관계형 데이터베이스는 원자가 일관성, 격리성 및 지속성(ACID, atomicity, consistency, isolation, and durability)의 속성을 제공합니다 1) 원자가는 완벽하게 실행하거나 혹은 전혀 실행하지 않는 트랜잭션을 필요로 합니다. 2) 일관성은 트랜잭션이 커밋되면 데이터가 데이터베이스 스키마를 준수하도록 요구합니다. 3) 격리성은 동시에 일어나는 트랜잭션들이 각기 별도로 실행되어야 함을 의미합니다. 4) 내구성은 예기치 못한 시스템 장애 또는 정전 시 마지막으로 알려진 상태로 복구하는 기능을 필요로 합니다.|NoSQL 데이터베이스는 흔히 수평으로 확장할 수 있는 보다 유연한 데이터 모델을 위해 관계형 데이터베이스의 일부 ACID 속성을 완화함으로써 조정합니다. 이로써 NoSQL 데이터베이스는 단일 인스턴스의 한계를 넘어 수평으로 확장해야 하는 사용 사례에서 높은 처리량, 낮은 지연 시간을 위한 탁월한 선택이 됩니다.|
```

콤마가 없어도 될 듯합니다.

2020-10-30 07:49 UTC, SeonHyungJo commented on Database/Types of Databases.md
> +|API|데이터를 저장 및 검색하기 위한 요청은 **SQL(구조화 질의 언어)**을 준수하는 쿼리를 사용하여 전달됩니다. 쿼리는 관계형 데이터베이스에 의해 구문 분석되고 실행됩니다.|**객체 기반 API**를 통해 앱 개발자가 데이터 구조를 쉽게 저장 및 검색할 수 있습니다. 파티션 키를 사용하면 앱에서 키-값 페어, 열 세트 또는 일련의 앱 객체 및 속
```suggestion
|API|데이터를 저장 및 검색하기 위한 요청은 **SQL(구조화 질의 언어)** 을 준수하는 쿼리를 사용하여 전달됩니다. 쿼리는 관계형 데이터베이스에 의해 구문 분석되고 실행됩니다.|**객체 기반 API**를 통해 앱 개발자가 데이터 구조를 쉽게 저장 및 검색할 수 있습니다. 파티션 키를 사용하면 앱에서 키-값 페어, 열 세트 또는 일련의 앱 객체 및 속성을 포함하는 반정형 문서를 검색할 수 있습니다.|
```

bold가 제대로 먹지 않았습니다.

2020-10-31 14:38 UTC, Dae-Hwa commented on Database/Types of Databases.md
> +|ACID 속성|	관계형 데이터베이스는 원자가, 일관성, 격리성 및 지속성(ACID, atomicity, consistency, isolation, and durability)의 속성을 제공합니다 1) 원자가는 완벽하게 실행하거나 혹은 전혀 실행하지 않는 트랜잭션을 필요로 합니다. 2) 일관성은 트랜잭션이 커밋되면 데이터가 데이터베이스 스키마를 준수하도록
원자성을 잘못 쓴 것 같은데요?

2020-11-01 02:49 UTC, EUNJIHA commented on Database/Types of Databases.md
> +|ACID 속성|	관계형 데이터베이스는 원자가, 일관성, 격리성 및 지속성(ACID, atomicity, consistency, isolation, and durability)의 속성을 제공합니다 1) 원자가는 완벽하게 실행하거나 혹은 전혀 실행하지 않는 트랜잭션을 필요로 합니다. 2) 일관성은 트랜잭션이 커밋되면 데이터가 데이터베이스 스키마를 준수하도록
atomicity 를 **원자가** 라고 번역한 것 같습니다. :)

2020-11-01 09:44 UTC, EUNJIHA commented on Database/Types of Databases.md
> +|ACID 속성|	관계형 데이터베이스는 원자가, 일관성, 격리성 및 지속성(ACID, atomicity, consistency, isolation, and durability)의 속성을 제공합니다 1) 원자가는 완벽하게 실행하거나 혹은 전혀 실행하지 않는 트랜잭션을 필요로 합니다. 2) 일관성은 트랜잭션이 커밋되면 데이터가 데이터베이스 스키마를 준수하도록
수정하였습니다

2020-11-01 09:51 UTC, BKJang approved these changes
은지님은 다양한 분야에 대해 공부하려고 노력하는 것 같아서 보기 좋아요 😄 
발표 때 얘기나왔던 것처럼 ORM과 같은 개념도 공부하면 좋을 것 같아요
고생하셨습니다 👍

2020-11-03 07:17 UTC, SeonHyungJo approved these changes
승인합니다. 👍

2020-11-03 07:17 UTC, merged