의존 역전 원칙
im-d-team/Dev-Docs pull request #174
Opened 2020-09-06 05:45 UTC by Dae-Hwa

2020-09-07 12:01 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2020-09-07 12:01 UTC, jigi-kim commented on CS/dependency-inversion-principle.md
> +주의해야 할 점은 위에서 살펴봤듯, 컴파일 타임 의존성을 변경시켜 구조를 유연하게 만드는 것이지 레이어의 순서를 뒤바꾸는것이 아니다. 상위 모듈은 하위 모듈에 의존하되, 의존 관계 사이에 추상화된 인터페이스를 둬서 유연성을 최대한 보장하도록 하는 것이 핵심이다.
```suggestion
주의해야 할 점은 위에서 살펴봤듯, 컴파일 타임 의존성을 변경시켜 구조를 유연하게 만드는 것이지 레이어의 순서를 뒤바꾸는 것이 아니다. 상위 모듈은 하위 모듈에 의존하되, 의존 관계 사이에 추상화된 인터페이스를 둬서 유연성을 최대한 보장하도록 하는 것이 핵심이다.
```

2020-09-09 10:16 UTC, Dae-Hwa commented on CS/dependency-inversion-principle.md
> +![dip01-layer.png](https://github.com/Dae-Hwa/diagrams/blob/master/dip/dip01-layer.png?raw=true)
이해가 잘 되었다니 다행이네요 😁 감사합니다

2020-09-11 18:11 UTC, jigi-kim approved these changes

2020-09-22 05:46 UTC, EUNJIHA approved these changes
상세하게 설명해주셔서 이해하기 수월했습니다. 승인합니다~

2020-10-31 12:19 UTC, dididy approved these changes

2020-11-01 09:52 UTC, BKJang approved these changes
승인할게요
항상 화이팅입니다 👍

2020-11-01 09:53 UTC, merged