20200928/eunjiha
im-d-team/Dev-Docs pull request #179
Opened 2020-09-27 05:18 UTC by EUNJIHA

2020-10-28 06:16 UTC, Dae-Hwa commented on Database/Query Builder ( Knex.js).md
> +물론, 날 SQL를 작성하는 것이 Knex.js를 통한 작성보다 쉬울 때가 많다. 그 때는 날 SQL문을 사용하고, Query Builder가 좀 더 수월하게 코드를 작성할 경우에는 Query Builder를 사용하여 작성하면 된다.
http://knexjs.org/#Raw
knex에 raw 쿼리도 지원해주네요.
sql 인잭션 방어를 위해서는 raw 쿼리를 사용하더라도 knex로 래핑하는 것이 좋아보이네요

2020-11-01 02:52 UTC, EUNJIHA commented on Database/Query Builder ( Knex.js).md
> +물론, 날 SQL를 작성하는 것이 Knex.js를 통한 작성보다 쉬울 때가 많다. 그 때는 날 SQL문을 사용하고, Query Builder가 좀 더 수월하게 코드를 작성할 경우에는 Query Builder를 사용하여 작성하면 된다.
해당 내용 덧붙여서 수정하였습니다 : )

2020-11-01 09:54 UTC, BKJang approved these changes
Query Builder나 ORM이 왜 Raw SQL을 쓰는 것이 비해 장점이 있는지 공부해보면 더 좋을 듯 합니다.
고생하셨어요 👍

2020-11-09 12:20 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2020-11-09 12:20 UTC, jigi-kim commented on Database/Query Builder ( Knex.js).md
> +**Knex.js** (pronounced /kəˈnɛks/) is a "batteries included" SQL query builder for **Postgres, MSSQL, MySQL, MariaDB, SQLite3, Oracle, and Amazon Redshift** designed to be flexible, portable, and fun
```suggestion
> **Knex.js** (pronounced /kəˈnɛks/) is a "batteries included" SQL query builder for **Postgres, MSSQL, MySQL, MariaDB, SQLite3, Oracle, and Amazon Redshift** designed to be flexible, portable, and fun to use. It features both traditional node style callbacks as well as a promise interface for cleaner async flow control, a stream interface, full featured query and **schema builders**, **transaction support (with savepoints)**, **connection pooling** and standardized responses between different query clients and dialects.
```
인용문으로 표현되면 더 좋을 것 같습니다.

2020-11-09 12:20 UTC, jigi-kim commented on Database/Query Builder ( Knex.js).md
> +		birth: userBirth
```suggestion
    birth: userBirth
```

2020-11-09 12:20 UTC, jigi-kim commented on Database/Query Builder ( Knex.js).md
> +물론, Raw SQL를 작성하는 것이 Knex.js를 통한 작성보다 쉬울 때가 많다. 그 때는 Raw SQL문을 사용하고 (Query Builder에서 Raw SQL도 지원한다), Raw SQL이 아닌 Query Builder가 좀 더 수월하게 코드를 작성할 경우에는 Query Builder를 사용하여 작성하면 된다.
```suggestion
물론, 날 SQL를 작성하는 것이 Knex.js를 통한 작성보다 쉬울 때가 많다. 그 때는 날 SQL문을 사용하고 (Query Builder에서 Raw SQL도 지원한다), 날 SQL이 아닌 Query Builder가 좀 더 수월하게 코드를 작성할 경우에는 Query Builder를 사용하여 작성하면 된다.
```
용어를 통일하는 편이 좋겠습니다. (혹은 반대로 `raw SQL`을 사용할 수도 있고요...)

2020-11-19 01:33 UTC, SeonHyungJo commented on Database/Query Builder ( Knex.js).md
> +참고로, 그냥 mysql 모듈을 사용하면 다음과 같은 오류가 나서 [구글링](https://www.inflearn.com/questions/3637)을 해보니 mysql2 모듈을 사용하여 해결할 수 있었다.
```suggestion
위의 예시에서 mysql 모듈을 사용하면 다음과 같은 오류 발생하여 [구글링](https://www.inflearn.com/questions/3637)을 해보니 mysql2 모듈을 사용하여 해결할 수 있었다.
```

위와 같은 수정은 어떤신가요?

2020-11-19 01:40 UTC, SeonHyungJo requested changes
리뷰남겼습니다. 확인부탁드립니다.

2020-11-19 01:40 UTC, SeonHyungJo commented on Database/Query Builder ( Knex.js).md
> +위를 바탕으로 다음과 같이 코드를 작성하면 짜잘한 일에 시간을 쏟지 않아도 된다.
```suggestion
위를 바탕으로 다음과 같이 코드를 작성하면 자잘한 일에 시간을 쏟지 않아도 된다.  
```

자잘한이 표준어인 듯 하여 수정요청드립니다.

2020-11-19 01:40 UTC, SeonHyungJo commented on Database/Query Builder ( Knex.js).md
> +});
```suggestion
// Using trx as a transaction object:
knex
  .transaction(function (trx) {
    const books = [
      { title: "Canterbury Tales" },
      { title: "Moby Dick" },
      { title: "Hamlet" },
    ];
    knex
      .insert({ name: "Old Books" }, "id")
      .into("catalogues")
      .transacting(trx)
      .then(function (ids) {
        books.forEach((book) => (book.catalogue_id = ids[0]));
        return knex("books").insert(books).transacting(trx);
      })
      .then(trx.commit)
      .catch(trx.rollback);
  })
  .then(function (inserts) {
    console.log(inserts.length + " new books saved.");
  })
  .catch(function (error) {
    // If we get here, that means that neither the 'Old Books' catalogues insert,
    // nor any of the books inserts will have taken place.
    console.error(error);
  });
```

약간의 인덴트 수정 요청드립니다.

2020-11-19 01:40 UTC, SeonHyungJo commented on Database/Query Builder ( Knex.js).md
> +      .transacting(trx)
위와 같이 작성해주시는 코딩 작성법은 깔금한 것 같습니다. 👍

2020-11-19 01:40 UTC, EUNJIHA commented on Database/Query Builder ( Knex.js).md
> +참고로, 그냥 mysql 모듈을 사용하면 다음과 같은 오류가 나서 [구글링](https://www.inflearn.com/questions/3637)을 해보니 mysql2 모듈을 사용하여 해결할 수 있었다.
좋습니다 반영하겠습니다 👍 @SeonHyungJo

2020-11-19 01:43 UTC, EUNJIHA commented on Database/Query Builder ( Knex.js).md
> +});
수정 감사합니다 👍

2020-11-19 05:14 UTC, SeonHyungJo approved these changes
승인합니다.

2020-11-19 10:23 UTC, dididy approved these changes
수고하셨습니다!

2020-11-19 12:55 UTC, jigi-kim approved these changes

2020-11-19 12:55 UTC, merged