JegalEun/Flow control
im-d-team/Dev-Docs pull request #180
Opened 2020-09-27 05:53 UTC by JegalEun

:pencil2: JegalEun / Add Flow control.md

2020-10-28 06:53 UTC, Dae-Hwa commented on Network/Flow control.md
> +이러한 `데이터 넘침`이 일어나지 않기 위해 수신 측에서 데이터를 그만 발송하라는 메시 지를 송신측에 통보해야 하는 피드백 메커니즘이 필요하다.
데이터 넘침 같은 용어는 영어가 워낙 익숙해 영어로도 같이 언급을 해주는게 보기 좋을 것 같습니다.

2020-10-28 06:53 UTC, Dae-Hwa commented on Network/Flow control.md
> +이를 `속도 조절`이라고 한다.
속도조절이 곧 흐름제어인것 맞나요?

2020-10-28 06:53 UTC, Dae-Hwa commented on Network/Flow control.md
> +매 세그먼트(Segment) 전송 시마다 `ACK`를 수신한 후 전송하게 되면 RTT가 길 경우 단위 시간당 데이터 전송량이 매우 떨어지게 된다.
문맥으로 파악할 수 있긴 하지만, RTT의 풀 네임이나 설명같은게 있다면 더 좋을 것 같습니다.

2020-11-01 09:55 UTC, BKJang commented on Network/Flow control.md
> +이러한 `데이터 넘침`이 일어나지 않기 위해 수신 측에서 데이터를 그만 발송하라는 메시 지를 송신측에 통보해야 하는 피드백 메커니즘이 필요하다.
```suggestion
이러한 `데이터 넘침`이 일어나지 않기 위해 수신 측에서 데이터를 그만 발송하라는 메시지를 송신측에 통보해야 하는 피드백 메커니즘이 필요하다.
```

2020-11-01 09:56 UTC, BKJang commented on Network/Flow control.md
> +먼저, 송신자(A)와 수신자(B)는 각자 버퍼를 준비한다.
`버퍼`라는게 뭔가요?

2020-11-01 09:57 UTC, BKJang commented on Network/Flow control.md
> +<img width="704" alt="윈도우 사이즈" src="https://user-images.githubusercontent.com/43868540/93662932-ced40680-fa9e-11ea-9d11-b0e0dce8bf14.png">
```suggestion
![flow_control]https://user-images.githubusercontent.com/43868540/93662932-ced40680-fa9e-11ea-9d11-b0e0dce8bf14.png
```

마크다운에서 이미지를 보여주는 문법입니다.

2020-11-01 09:58 UTC, BKJang requested changes
몇 가지 질문과 수정했으면 하는 사항들을 커멘트로 남겼습니다 😄

2020-11-03 09:33 UTC, JegalEun commented on Network/Flow control.md
> +이러한 `데이터 넘침`이 일어나지 않기 위해 수신 측에서 데이터를 그만 발송하라는 메시 지를 송신측에 통보해야 하는 피드백 메커니즘이 필요하다.
영어로 표현하는 것이 친숙하여 수정하였습니다👍

2020-11-03 09:34 UTC, JegalEun commented on Network/Flow control.md
> +이를 `속도 조절`이라고 한다.
넵 ㅎㅎ 혼동이 있을거같아 흐름제어로 수정하였습니다.

2020-11-03 09:35 UTC, JegalEun commented on Network/Flow control.md
> +매 세그먼트(Segment) 전송 시마다 `ACK`를 수신한 후 전송하게 되면 RTT가 길 경우 단위 시간당 데이터 전송량이 매우 떨어지게 된다.
RTT에 대한 설명 추가하였습니다 👍

2020-11-03 09:35 UTC, JegalEun commented on Network/Flow control.md
> +이러한 `데이터 넘침`이 일어나지 않기 위해 수신 측에서 데이터를 그만 발송하라는 메시 지를 송신측에 통보해야 하는 피드백 메커니즘이 필요하다.
수정하였습니다~

2020-11-03 09:38 UTC, JegalEun commented on Network/Flow control.md
> +<img width="704" alt="윈도우 사이즈" src="https://user-images.githubusercontent.com/43868540/93662932-ced40680-fa9e-11ea-9d11-b0e0dce8bf14.png">
앗 앞으로 저 문법으로 사용할게요 👍

2020-11-03 09:39 UTC, JegalEun commented on Network/Flow control.md
> +먼저, 송신자(A)와 수신자(B)는 각자 버퍼를 준비한다.
송신자와 수신자가 각각 가지고 있는 저장용량이라고 생각하시면 됩니다!

2020-11-03 12:15 UTC, BKJang approved these changes
승인할게요~ 고생하셨습니다 👍

2020-11-19 01:46 UTC, SeonHyungJo requested changes
간단한 리뷰 남겼습니다. 확인 부탁드립니다.

2020-11-19 01:46 UTC, SeonHyungJo commented on Network/Flow control.md
> +최근에 네트워크에 관심이 생겨 네트워크에 대해 앞으로 조금씩 정리해볼 예정이다.
흥미롭군요 기대하고 있습니다.

2020-11-19 01:46 UTC, SeonHyungJo commented on Network/Flow control.md
> +무슨 문제가 발생하냐?
```suggestion
무슨 문제가 발생하나?
```

냐와 나 중 고민이 되는군요

2020-11-19 01:46 UTC, SeonHyungJo commented on Network/Flow control.md
> +수신 측에서 수신된 데이터를 저장용량(queue)에 저장을 하고 처리해서 위에 계층으로 서비스를 하게 되는데,
```suggestion
수신 측에서 수신된 데이터를 저장용량(queue)에 저장하고 처리해서 위에 계층으로 서비스를 하게 되는데,
```

제가 글을 쓰는 습관과 비슷하군요 글을 적을 때는 저장을 하고 보다는 저장하고가 좋은거 같습니다.

2020-11-19 01:46 UTC, SeonHyungJo commented on Network/Flow control.md
> +이것을 `오버플로우`이라고 표현한다.
글에서 처음 언급되는 영어 단어는 영어도 같이 표기하는 방법도 좋은 방법입니다.

2020-11-19 01:46 UTC, SeonHyungJo commented on Network/Flow control.md
> +다음 시간에는 `호스트`와 `네트워크` 상의 데이터 처리를 효율적으로 하는 `Congestion control`에 대해 알아볼 것이다.
즐거운 시리즈 물이군요

2020-11-22 04:08 UTC, JegalEun commented on Network/Flow control.md
> +무슨 문제가 발생하냐?
생각해보니 냐보다는 무슨 문제가 발생할까? 는 어떤가용

2020-11-22 04:23 UTC, JegalEun commented on Network/Flow control.md
> +수신 측에서 수신된 데이터를 저장용량(queue)에 저장을 하고 처리해서 위에 계층으로 서비스를 하게 되는데,
ㅋㅋㅋㅋ 유의하겠습니다

2020-11-22 04:23 UTC, JegalEun commented on Network/Flow control.md
> +이것을 `오버플로우`이라고 표현한다.
수정하였습니다~

2020-11-22 06:37 UTC, EUNJIHA reviewed
흥미로운 주제네요 :) 몇 가지 리뷰 확인 부탁드립니다.

2020-11-22 06:37 UTC, EUNJIHA commented on Network/Flow control.md
> +위와 같은 이유로 효율적이지 않지만 가장 큰 이유는 일정 시간 동안 한 개의 Frame밖에 보내지 못한다.
```suggestion
위와 같은 문제로 효율적이지 않지만 가장 큰 문제는 일정 시간 동안 한 개의 Frame밖에 보내지 못한다는 것이다.
```

2020-11-22 06:37 UTC, EUNJIHA commented on Network/Flow control.md
> +위와 같은 이유로 효율적이지 않지만 가장 큰 이유는 일정 시간 동안 한 개의 Frame밖에 보내지 못한다.
매끄러운 문장으로 수정해봤어요!

2020-11-22 06:37 UTC, EUNJIHA commented on Network/Flow control.md
> +A는 자신의 버퍼에 데이터를 쓰고, B는 자신의 버퍼에서 데이터를 읽어오는 것이다.
이 문장이 무슨 뜻인지 잘 모르겠습니다. 상세하게 설명해주실 수 있을까요?

2020-11-24 07:18 UTC, JegalEun commented on Network/Flow control.md
> +A는 자신의 버퍼에 데이터를 쓰고, B는 자신의 버퍼에서 데이터를 읽어오는 것이다.
윈도우 크기가 4라고 친다면,
A(송신자)는 버퍼에 4만큼 데이터를 차례로 저장을 할 것입니다. 그리고 B(수신자)로 데이터를 한꺼번에 보내게 됩니다.  
B(수신자)는 하나씩 데이터가 온 순서대로 버퍼에 저장하게 됩니다. 그리고 버퍼에 저장된 데이터를 읽어들여 seq#같은 정보를 확인하여 데이터가 정상적으로 도착했는지를 알 수 있습니다.

아직 설명이 부족하다면 편하게 또 남겨주세요 : )

2020-11-24 07:20 UTC, JegalEun commented on Network/Flow control.md
> +위와 같은 이유로 효율적이지 않지만 가장 큰 이유는 일정 시간 동안 한 개의 Frame밖에 보내지 못한다.
좋아요 👍

2020-11-30 03:35 UTC, Dae-Hwa approved these changes

2020-12-02 05:59 UTC, dididy approved these changes
수고 많으셨습니다! 개인적인 의문점은 코멘트 남겼습니다!

2020-12-02 05:59 UTC, dididy commented on Network/Flow control.md
> +1. 만약 B가 자신의 `RWS`가 3,000 bytes라고 하면 A는 `30`개의 패킷을 전송한다.(window = 30)
슬라이딩 윈도우 버퍼 내부적인 단위는 패킷이고 윈도우 사이즈만큼 묶은 패킷 묶음이 윈도우라고 이해했는데 맞나요?

2020-12-02 05:59 UTC, dididy commented on Network/Flow control.md
> +B의 데이터를 읽는 속도가 떨어질 경우, WS(Window Size)를 줄여가며 송신자의 데이터 전송을 컨트롤할 수 있다.
이부분은 슬라이딩 윈도우 내부적으로 자동으로 처리되는 것인가요? 혹은 윈도우 사이즈를 사용자가 설정할 수 있다는 의미인가요?

2020-12-03 03:45 UTC, SeonHyungJo commented on Network/Flow control.md
> +무슨 문제가 발생하냐?
@JegalEun 좋은 의견입니다. 그렇게 적용하시는게 좋은거 같습니다.

2020-12-03 10:57 UTC, EUNJIHA commented on Network/Flow control.md
> +A는 자신의 버퍼에 데이터를 쓰고, B는 자신의 버퍼에서 데이터를 읽어오는 것이다.
이해했습니다. 감사합니다 👍

2020-12-03 10:58 UTC, EUNJIHA approved these changes
승인합니다!

2020-12-05 14:10 UTC, JegalEun commented on Network/Flow control.md
> +무슨 문제가 발생하냐?
적용완료하였습니다~

2020-12-05 14:12 UTC, JegalEun commented on Network/Flow control.md
> +1. 만약 B가 자신의 `RWS`가 3,000 bytes라고 하면 A는 `30`개의 패킷을 전송한다.(window = 30)
네 맞습니다 :)

2020-12-05 14:16 UTC, JegalEun commented on Network/Flow control.md
> +B의 데이터를 읽는 속도가 떨어질 경우, WS(Window Size)를 줄여가며 송신자의 데이터 전송을 컨트롤할 수 있다.
내부적으로 송신 측에서 윈도우 사이즈를 조절합니다.

2020-12-06 02:52 UTC, SeonHyungJo approved these changes
승인합니다

2020-12-06 02:53 UTC, merged