Browser Cookie
im-d-team/Dev-Docs pull request #190
Opened 2020-10-11 04:41 UTC by SeonHyungJo

2020-11-03 12:16 UTC, BKJang commented on Browser/Cookie.md
> +위 사진은 Chrome 개발자 도구에 들어가서 Application Tab을 누르게 되면 왼쪽 메뉴에 보이는 Storage로 총 **5개**가 있다. 그중 가장 아래에 있는 Cookie에 대해서 알아보자
```suggestion
위 사진은 Chrome 개발자 도구에 들어가서 Application Tab을 누르게 되면 왼쪽 메뉴에 보이는 Storage로 총 **5개**가 있다. 그중 가장 아래에 있는 Cookie에 대해서 알아보자
```
```suggestion
위 사진은 Chrome 개발자 도구에 들어가서 Application Tab을 누르게 되면 왼쪽 메뉴에 보이는 Storage로 총 **5개**가 있다. 그 중 가장 아래에 있는 Cookie에 대해서 알아보자
```

2020-11-03 12:21 UTC, BKJang commented on Browser/Cookie.md
> +### samesite 옵션
최근 Chrome의 samsite 관련 이슈가 있었는데 해당 내용이 초반에 추가되면 좋을 것 같습니다.
어떻게 생각하시나요?

https://brocess.tistory.com/263

2020-11-03 12:22 UTC, BKJang requested changes
의견 제안드렸습니다 확인 후 피드백 부탁드려요 :)
이 내용을 미리 알았으면 좋았을텐데요 😂

2020-11-04 04:58 UTC, SeonHyungJo commented on Browser/Cookie.md
> +### samesite 옵션
해당 부분은 발표때 언급이 있었는데, 개인적으로 이슈보다는 Default값이 none에서 lax로 바뀐거 밖에 없다고 생각하는 입장으로 원래 개발 시 명시적으로 samesite를 넣는게 맞다고 생각해서 꼭 넣어야 하나 라고 생각하고 있습니다. @BKJang

2020-11-04 14:59 UTC, BKJang commented on Browser/Cookie.md
> +### samesite 옵션
그렇다면 제안드린 링크라도 추가해두는건 어떨까요? 말씀하신대로 이슈라고 보기 힘들 순 있지만, none에서 lax로 값이 바뀐 이유는 있을테니까요.

2020-11-05 02:16 UTC, SeonHyungJo commented on Browser/Cookie.md
> +### samesite 옵션
네 좋습니다 추가하겠습니다.

2020-11-09 13:32 UTC, JegalEun commented on Browser/Cookie.md
> +3. 서버는 브라우저가 보낸 요청 헤더의 세션 식별자를 읽어 사용자를 식별한다.
1단계에서 서버는 고유값(식별자)를 설정해 다시 브라우저에게 전송하나요?

2020-11-09 14:11 UTC, JegalEun commented on Browser/Cookie.md
> +`samesite=lax`는 사용자 경험을 해치지 않으면서 XSRF 공격을 막을 수 있는 느슨한 접근법이다.
사용자 경험이라는 것은 사용자 식별이라고 이해하면 될까요?

2020-11-09 14:17 UTC, JegalEun approved these changes
미리 승인합니다~ 수고하셨습니다 👍

2020-11-10 01:38 UTC, SeonHyungJo commented on Browser/Cookie.md
> +`samesite=lax`는 사용자 경험을 해치지 않으면서 XSRF 공격을 막을 수 있는 느슨한 접근법이다.
@JegalEun 여기서 사용자는 개발자를 의미하는 것 입니다. 다른게 이해될 수 있으니 변경해야 겠군요. 사용자의 식별보다는 이미 사용되는 툴들을 해치지않는다는 의미로 생각하시면 됩니다.

2020-11-10 01:38 UTC, SeonHyungJo commented on Browser/Cookie.md
> +3. 서버는 브라우저가 보낸 요청 헤더의 세션 식별자를 읽어 사용자를 식별한다.
1단계는 오히려 로그인을 요청해서 서버에서 `Set-Cookie`로 내려주는 것을 의미합니다.

2020-11-19 01:48 UTC, SeonHyungJo commented on Browser/Cookie.md
> +`samesite=lax`는 사용자 경험을 해치지 않으면서 XSRF 공격을 막을 수 있는 느슨한 접근법이다.
확인 후 재승인 부탁드립니다. @JegalEun

2020-11-19 01:52 UTC, SeonHyungJo commented on Browser/Cookie.md
> +### samesite 옵션
@BKJang 추가완료했습니다.

2020-11-22 03:31 UTC, JegalEun approved these changes
승인합니다~ 수고하셨습니다 :)

2020-11-22 08:14 UTC, EUNJIHA reviewed
흥미로운 주제네요! 리뷰 확인 부탁드립니다 :)

2020-11-23 15:22 UTC, BKJang approved these changes
피드백 반영 감사합니다 😄

2020-11-30 04:12 UTC, Dae-Hwa approved these changes

2020-11-30 13:18 UTC, SeonHyungJo commented on Browser/Cookie.md
> +document.cookie = "user=SeonHyungJo; domain=imdev.com"
약간의 보충 설명이 필요해 보입니다. 제가 이해가 안되서요 @EUNJIHA

2020-12-02 05:23 UTC, dididy approved these changes
쿠키의 용도와 사용법 보안을 강화하는 부분에 대해서 잘 이해할 수 있었습니다. 감사합니다!

2020-12-02 05:24 UTC, merged