congestion control.md
im-d-team/Dev-Docs pull request #192
Opened 2020-10-25 06:12 UTC by JegalEun

:pencil2: JegalEun / Add Congestion control.md

2020-11-04 14:51 UTC, BKJang commented on Network/congestion control.md
> +만약, 한 라우터에 데이터가 몰릴 경우(=혼잡할 경우) 라우터는 자신에게 온 데이터를 모두 처리할 수 없다. 그렇다면 송신 측에서 데이터를 다시 재전송을 하게 되고 혼잡을 가중해 오버플로우가 발생해 데이터 손실을 야기시킨다.
```suggestion
만약, 한 라우터에 데이터가 몰릴 경우(=혼잡할 경우) 라우터는 자신에게 온 데이터를 모두 처리할 수 없다. 그렇다면 송신 측에서 데이터를 다시 재전송을 하게 되고 혼잡을 가중하고 오버플로우가 발생해 데이터 손실을 야기시킨다.
```

2020-11-04 14:52 UTC, BKJang commented on Network/congestion control.md
> +즉, 네트워크에 아직 별문제가 없어 전송 속도를 더 빠르게 하기 위해서 `cwnd`를 **1씩 증가**시킨다. 하지만 중간에 데이터가 유실되거나 응답이 오지 않는 등의 혼잡 상태가 감지되면 `cwnd`를 **반**으로 줄인다.
cwnd에 대한 설명이 좀 더 있으면 이해가 더 쉬울 것 같습니다.

2020-11-04 14:53 UTC, BKJang commented on Network/congestion control.md
> +<img width="608" alt="AIMD" src="https://user-images.githubusercontent.com/43868540/94355427-eb83c600-00be-11eb-83aa-cf7377e5df8c.png">
```suggestion
![AIMD](https://user-images.githubusercontent.com/43868540/94355427-eb83c600-00be-11eb-83aa-cf7377e5df8c.png)
```

2020-11-04 14:56 UTC, BKJang commented on Network/congestion control.md
> +위 그림을 보면 9라운드부터 타호와 리노의 모양이 달라지는 것을 확인할 수 있다.
```suggestion
위 그림을 보면 9라운드부터 Tahoe와 Reno의 모양이 달라지는 것을 확인할 수 있다.
```

용어를 통일하는게 좋을 것 같습니다. :)

2020-11-04 14:57 UTC, BKJang requested changes
몇 가지 수정 사항과 추가되면 좋을 것 같은 내용에 대해 남겼습니다.
점점 잘하시는 것 같아서 보기 좋네요 👍

2020-11-09 11:55 UTC, jigi-kim approved these changes

2020-11-09 14:25 UTC, JegalEun commented on Network/congestion control.md
> +위 그림을 보면 9라운드부터 타호와 리노의 모양이 달라지는 것을 확인할 수 있다.
수정하였습니다 ~

2020-11-09 14:26 UTC, JegalEun commented on Network/congestion control.md
> +<img width="608" alt="AIMD" src="https://user-images.githubusercontent.com/43868540/94355427-eb83c600-00be-11eb-83aa-cf7377e5df8c.png">
수정하였습니다~

2020-11-09 14:27 UTC, JegalEun commented on Network/congestion control.md
> +즉, 네트워크에 아직 별문제가 없어 전송 속도를 더 빠르게 하기 위해서 `cwnd`를 **1씩 증가**시킨다. 하지만 중간에 데이터가 유실되거나 응답이 오지 않는 등의 혼잡 상태가 감지되면 `cwnd`를 **반**으로 줄인다.
용어 설명 추가하였씁니다. ~

2020-11-09 14:27 UTC, JegalEun commented on Network/congestion control.md
> +만약, 한 라우터에 데이터가 몰릴 경우(=혼잡할 경우) 라우터는 자신에게 온 데이터를 모두 처리할 수 없다. 그렇다면 송신 측에서 데이터를 다시 재전송을 하게 되고 혼잡을 가중해 오버플로우가 발생해 데이터 손실을 야기시킨다.
수정완료하였습니당

2020-11-23 15:24 UTC, BKJang approved these changes
피드백 반영 감사합니다 👍  승인할게요~

2020-12-03 04:39 UTC, SeonHyungJo approved these changes

2020-12-06 03:07 UTC, dididy approved these changes
혼잡 제어는 어떨 때 사용되는 것인지 배경 설명 부분과 각 알고리즘에 대한 잘 설명되어 있네요. 배워갑니다 👍

2020-12-06 03:08 UTC, merged