Bomb Lab(1)
im-d-team/Dev-Docs pull request #193
Opened 2020-10-31 12:43 UTC by dididy

2020-11-05 07:47 UTC, BKJang commented on CS/Bomb-Lab(1).md
> +Bomb Lab은 Carnegie Mellon University의 시스템 프로그래밍 과제인 Lab 시리즈 중 하나이다. 과제에는 bomb라는 바이너리 파일이 제공된다. 과제의 목적은 gdb를 이용해 해당 파일을 리버스 엔지니링 하여 총 6단계의 문구를 찾아 폭탄을 해체하는 것이다. 과제의 특성상 어셈블리를 분석해야 하기 때문에 문제를 해결하는 과정에서
`gdb`에 대한 간단한 설명이 인용구 형태로 적히면 좋을듯 합니다.

2020-11-05 07:48 UTC, BKJang commented on CS/Bomb-Lab(1).md
> +operand 앞에 붙는 기호 중 `$`는 상수 `%`는 레지스터를 나타낸다.
```suggestion
operand 앞에 붙는 기호 중 `$`와 상수 `%`는 레지스터를 나타낸다.
```
문장의 의미가 이상해서 그런데 위와 같은 문장을 의도한게 맞나요?

2020-11-05 07:49 UTC, BKJang commented on CS/Bomb-Lab(1).md
> +- AT&T 방식에서는 `instruction src, dest` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
```suggestion
- AT&T 방식에서는 `[instruction] [src], [dest]` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
```

위와 같이 표현해주는게 좀 더 이해하기 쉬울 것 같은데 어떠신가요?

2020-11-05 07:52 UTC, BKJang requested changes
한 가지 궁금한게 있는데 Bomb Lab이라는 내용에 대해서 알게된 경로가 있을까요?

2020-11-05 08:31 UTC, dididy commented
> 한 가지 궁금한게 있는데 Bomb Lab이라는 내용에 대해서 알게된 경로가 있을까요?

@BKJang 지금 수업듣고있는 시스템프로그래밍 실습 중 하나라 겸사겸사 주제로 정했어요. 교수님이 카네기멜론 대학교를 너무 좋아하셔서(포닥을 하셨다고 합니다) 실습도 그대로 들고오셨습니다..

저번에 발표하고 리뷰받은 내용도 반영해서 수정해보도록 하겠습니다.

2020-11-09 11:50 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2020-11-09 11:50 UTC, jigi-kim commented on CS/Bomb-Lab(1).md
> +operand 앞에 붙는 기호 중 `$`는 상수 `%`는 레지스터를 나타낸다.
```suggestion
operand 앞에 붙는 기호 중 `$`는 상수, `%`는 레지스터를 나타낸다.
```
위 문장을 의도한 것으로 보이네요.

2020-11-09 11:50 UTC, jigi-kim commented on CS/Bomb-Lab(1).md
> +- AT&T 방식에서는 `instruction src, dest` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
아래 instruction table은 `x86` ISA에 대한 설명으로 보이는데, 이에 대한 보충 설명이 필요할 것 같습니다.

위 내용으로는 `instruction src, dest` 형태라고 하는데, 왜 표의 설명은 `instruction dest, src` 형태로 설명을 하는 것인지... 개념을 처음 접하는 입장에서는 혼란을 줄 수 있을 것 같습니다.

2020-11-09 11:50 UTC, jigi-kim commented on CS/Bomb-Lab(1).md
> +## GDB
위에서 @BKJang 님이 커멘트 해주었지만, GDB에 대한 간략한 소개가 있으면 이해에 더 도움이 될 것 같네요.

2020-11-18 18:20 UTC, dididy commented on CS/Bomb-Lab(1).md
> +- AT&T 방식에서는 `instruction src, dest` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
반영하였습니다!

2020-11-18 18:21 UTC, dididy commented on CS/Bomb-Lab(1).md
> +operand 앞에 붙는 기호 중 `$`는 상수 `%`는 레지스터를 나타낸다.
네 맞습니다. 반영하였습니다!

2020-11-18 18:21 UTC, dididy commented on CS/Bomb-Lab(1).md
> +Bomb Lab은 Carnegie Mellon University의 시스템 프로그래밍 과제인 Lab 시리즈 중 하나이다. 과제에는 bomb라는 바이너리 파일이 제공된다. 과제의 목적은 gdb를 이용해 해당 파일을 리버스 엔지니링 하여 총 6단계의 문구를 찾아 폭탄을 해체하는 것이다. 과제의 특성상 어셈블리를 분석해야 하기 때문에 문제를 해결하는 과정에서
네 빠르게 추가해보도록 하겠습니다.

2020-11-18 18:21 UTC, dididy commented on CS/Bomb-Lab(1).md
> +## GDB
넵 알겠습니다~

2020-11-18 18:21 UTC, dididy commented on CS/Bomb-Lab(1).md
> +- AT&T 방식에서는 `instruction src, dest` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
네네 이부분은 자료를 새로 찾던지 설명을 추가하던지 하겠습니다!

2020-11-23 15:26 UTC, BKJang approved these changes
리뷰 반영 감사합니다. 고생하셨습니다 👍 
새로운 주제라 재밌었어요ㅎㅎ

2020-12-03 14:21 UTC, SeonHyungJo approved these changes
간단한 comment를 남겼습니다. 바로 승인하겠습니다.

2020-12-03 14:21 UTC, SeonHyungJo commented on CS/Bomb-Lab(1).md
> +![](https://t1.daumcdn.net/cfile/tistory/2562654F54B3CAA308)
사진의 경우 대괄호 안에 사진에 대한 정보를 간략하게 설명할 수 있는 alt 태그 정보를 넣어주는 것이 좋습니다.

2020-12-03 14:21 UTC, SeonHyungJo commented on CS/Bomb-Lab(1).md
> +![](https://user-images.githubusercontent.com/16266103/97117767-47d31780-1749-11eb-97ab-37041e56b5bd.png)
alt 내용을 추가하는게 좋습니다.

2020-12-03 14:21 UTC, SeonHyungJo commented on CS/Bomb-Lab(1).md
> +`phase_3` ~ `phase_6` 에 입력될 올바른 문자열을 찾는 방법에 대해서는 다음에 작성하게 될 Bomb Lab(2) 문서에서 설명해보려고 한다.
기대하겠습니다.

2020-12-05 14:50 UTC, JegalEun commented on CS/Bomb-Lab(1).md
> +`L1:`은 기계어 코드로 번역되지 않고 분기 명령(jmp) 등에서 참조될 때에 번지의 계산에 사용된다. `mov`는 operand2의 값을 operand1에 할당할 때 사용한다.
분기 명령은 무엇인가요?

2020-12-06 03:17 UTC, dididy commented
피드백 부분 차주 월요일 이후 반영하겠습니다. 반영이 늦어 죄송합니다.. 마감에 가까운 것들이 너무 많네요 ㅠㅠ

2020-12-06 03:18 UTC, dididy commented on CS/Bomb-Lab(1).md
> +![](https://t1.daumcdn.net/cfile/tistory/2562654F54B3CAA308)
넵 알겠습니다!

2020-12-06 03:18 UTC, dididy commented on CS/Bomb-Lab(1).md
> +`phase_3` ~ `phase_6` 에 입력될 올바른 문자열을 찾는 방법에 대해서는 다음에 작성하게 될 Bomb Lab(2) 문서에서 설명해보려고 한다.
잘 준비해보도록 하겠습니다..!

2020-12-06 03:21 UTC, dididy commented on CS/Bomb-Lab(1).md
> +`L1:`은 기계어 코드로 번역되지 않고 분기 명령(jmp) 등에서 참조될 때에 번지의 계산에 사용된다. `mov`는 operand2의 값을 operand1에 할당할 때 사용한다.
일반적인 프로그래밍 언어의 if문에 해당한다고 보시면 됩니다. 어셈블리에서는 jmp를 이용해 분기처리를 합니다.

[어셈블리 분기문](https://itsaessak.tistory.com/247) 

위 링크에 자세하게 설명되어있고 문서에 반영해보도록 하겠습니다!

2020-12-07 10:31 UTC, dididy commented on CS/Bomb-Lab(1).md
> +Bomb Lab은 Carnegie Mellon University의 시스템 프로그래밍 과제인 Lab 시리즈 중 하나이다. 과제에는 bomb라는 바이너리 파일이 제공된다. 과제의 목적은 gdb를 이용해 해당 파일을 리버스 엔지니링 하여 총 6단계의 문구를 찾아 폭탄을 해체하는 것이다. 과제의 특성상 어셈블리를 분석해야 하기 때문에 문제를 해결하는 과정에서
반영하였습니다!

2020-12-07 16:33 UTC, jigi-kim commented on CS/Bomb-Lab(1).md
> +- AT&T 방식에서는 `instruction src, dest` 인 것을 감안하고 참고해야 한다. (LEA, MOVE 등)
@dididy 수정 내용 확인했습니다. resolve 합니다.

2020-12-07 16:33 UTC, jigi-kim approved these changes

2020-12-09 04:30 UTC, EUNJIHA reviewed
흥미롭네요! 리뷰 확인 부탁드립니다 :)

2020-12-09 04:30 UTC, EUNJIHA commented on CS/Bomb-Lab(1).md
> +## 사전지식
사전지식 란이 있어서 더 이해하기가 수월하네요!

2020-12-09 04:30 UTC, EUNJIHA commented on CS/Bomb-Lab(1).md
> +
코드를 해석할 때, callq 부분을 먼저 해석하는 것이 전체 코드를 이해하는 데에 용이해서 그런 것인가요?

2020-12-09 04:30 UTC, EUNJIHA commented on CS/Bomb-Lab(1).md
> +여기까지 진행해보면 피보나치 수열의 규칙을 찾을 수 있다. `0 1 1 2 3 5`를 `phase_2` 함수의 입력값으로 넣게 되면 `phase_3`으로 넘어갈 수 있다.
피보나치 수열 구칙을 찾은 것은, +57까지 해석 하고 나서 뒷 부분도 이와 비슷하게 진행되겠다를 유추한 것인가요?

2020-12-15 19:31 UTC, dididy commented on CS/Bomb-Lab(1).md
> +
네 맞습니다. call은 어셈블리에서 함수 호출시 사용하는 명령어입니다. 일반적으로 코드를 볼 때와 같이 정의된 함수를 파악하면 전체 흐름을 보는데 도움이 되는 것과 유사한데 어셈블리는 직관적으로 파악하기 편한 구조가 아니기 때문에 함수에 대해 이해하고나면 구조 파악이 잘 되었어서 글의 진행이 이런식으로 되었네요

2020-12-15 19:33 UTC, dididy commented on CS/Bomb-Lab(1).md
> +여기까지 진행해보면 피보나치 수열의 규칙을 찾을 수 있다. `0 1 1 2 3 5`를 `phase_2` 함수의 입력값으로 넣게 되면 `phase_3`으로 넘어갈 수 있다.
네네 과제 자체가 리버스 엔지니어링이다보니 어느정도 직관에 의존하는 부분이 있습니다!

2020-12-17 13:33 UTC, EUNJIHA approved these changes
승인합니다!

2020-12-17 13:35 UTC, merged