관점(관심) 지향 프로그래밍
im-d-team/Dev-Docs pull request #194
Opened 2020-10-31 14:50 UTC by Dae-Hwa

2020-11-09 11:31 UTC, jigi-kim requested changes
문서 내용에 대한 질문 및 수정/확인 요청을 남깁니다.

2020-11-09 11:31 UTC, jigi-kim commented on CS/aspect-oriented-programming.md
> + 	public void doSomething() {
```suggestion
    public void doSomething() {
```

2020-11-09 11:31 UTC, jigi-kim commented on CS/aspect-oriented-programming.md
> +aspect는 기존 프로그램의 동작과 관계없이 추가, 변경 가능해야 한다. 관점 지향 언어들은 기존 프로그램의 동작과 관계없이 실행 지점을 설정할 수 있도록 지원해주는데 이를 **join point**라고 한다. 메소드 실행(method execution)이나 메소드 콜(method call)과 같은 시스템의 실행을 포인트로 지정하는 것이다.
`관점 지향 언어`에는 어떠한 언어들이 있나요?

개인적으로 생소한 개념인지라 관련된 언어에 어떠한 것들이 있는지 궁금하네요.

2020-11-09 11:31 UTC, jigi-kim commented on CS/aspect-oriented-programming.md
> +위에서 본 개념들만 살펴봤을 때는 AOP가 구세주처럼 느껴질 수 있다. 하지만 AOP에도 문제 발생 가능성이 있다. AOP를 사용할 경우 아래 사항들을 인지한 뒤 도입해야 한다.
AOP 방식의 예제 코드가 있으면 좋을 것 같습니다.

관심사를 찾아 묶어낸다는 개념 자체는 좋아보이지만, 실제 예제가 없으니 좀 와닿지 않는 느낌도 있습니다.

2020-11-09 13:39 UTC, BKJang approved these changes
승인합니다~ 👍

2020-12-09 05:14 UTC, EUNJIHA reviewed
흥미로운 주제입니다. 리뷰 확인 부탁드립니다 :)

2020-12-09 05:14 UTC, EUNJIHA commented on CS/aspect-oriented-programming.md
> +셋째로 동시에 여러 개의 aspect가 적용될 경우 문제가 발생할 수 있으며, aspect가 자기 자신에게 적용된다면 의도하지 않은 결과가 나올 수 있다.
> aspect가 자기 자신에게 적용된다면

이것이 어떤 의미인지 궁금합니다. 예시가 있을까요?

2020-12-09 05:14 UTC, EUNJIHA commented on CS/aspect-oriented-programming.md
> +첫째로 언어 차원에서 타겟 클래스에 표시하지 않도록 되어있다면 해당 코드 작성자 이외에는 해당 코드에 aspect가 적용되는 것인지 알 수 없다. 해당 코드 이외에 전체적인 시스템의 흐름이 파악되어야 정확히 이해할 수 있다. 특히 pointcut이 훼손될 경우 찾아내는 데 큰 어려움을 겪을 수 있다.
Spring은 타겟 클래스에 표시 하도록 되어 있나요? 아니라면 보통 명시해주는 방식을 사용하나요?

2020-12-12 07:58 UTC, SeonHyungJo approved these changes
간단한 질문하나 올렸습니다. 바로 승인하겠습니다.

2020-12-12 07:58 UTC, SeonHyungJo commented on CS/aspect-oriented-programming.md
> +가장 쉬운 예시로는 로그를 쌓고자 하는 경우를 들 수 있다. 클래스 혹은 함수단위의 로그를 쌓고자 하는 경우 해당 객체의 핵심 기능과 별개의 코드가 필요하다.
로그는 명확하게 느낌이 오는데, 다른 것은 잘 안 떠오는데 하나만 더 예제를 들 수 있을까요?

2020-12-15 01:13 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> +가장 쉬운 예시로는 로그를 쌓고자 하는 경우를 들 수 있다. 클래스 혹은 함수단위의 로그를 쌓고자 하는 경우 해당 객체의 핵심 기능과 별개의 코드가 필요하다.
수평관심사에 대해 다시 한 번 생각해보시면 좋을 것 같습니다. 연관이 없는 객체들에서 공통적으로 사용될 만한 요소들을 떠올리면 될 것 같은데요. 보일러 플레이트를 줄이기 위한 방법 중 하나로 생각할 수도 있겠네요.
예시로는 공통적인 예외처리나 로그인 인증, 트랜잭션 적용 등이 있을 것 같습니다.

2020-12-15 01:21 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> +첫째로 언어 차원에서 타겟 클래스에 표시하지 않도록 되어있다면 해당 코드 작성자 이외에는 해당 코드에 aspect가 적용되는 것인지 알 수 없다. 해당 코드 이외에 전체적인 시스템의 흐름이 파악되어야 정확히 이해할 수 있다. 특히 pointcut이 훼손될 경우 찾아내는 데 큰 어려움을 겪을 수 있다.
@EUNJIHA xml로 작성하여 분리할 수 있고 어노테이션을 이용하여 명시해줄 수 있는데 요즘은 어노테이션이 많이 쓰이는 것 같아요.

2020-12-15 01:23 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> +셋째로 동시에 여러 개의 aspect가 적용될 경우 문제가 발생할 수 있으며, aspect가 자기 자신에게 적용된다면 의도하지 않은 결과가 나올 수 있다.
@EUNJIHA aspect가 실행단위인데 어떤 코드의 실행 조건이 스스로 실행되는 것이라면 재귀적인 코드가 되겠죠?

2020-12-15 01:23 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> +위에서 본 개념들만 살펴봤을 때는 AOP가 구세주처럼 느껴질 수 있다. 하지만 AOP에도 문제 발생 가능성이 있다. AOP를 사용할 경우 아래 사항들을 인지한 뒤 도입해야 한다.
@jigi-kim 예제는 플랫폼마다 다른데, 주제가 공통적인 개념 부분에 대한 것이라 함께 정리하기에는 무리가 있다고 판단했습니다.

2020-12-15 01:43 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> +aspect는 기존 프로그램의 동작과 관계없이 추가, 변경 가능해야 한다. 관점 지향 언어들은 기존 프로그램의 동작과 관계없이 실행 지점을 설정할 수 있도록 지원해주는데 이를 **join point**라고 한다. 메소드 실행(method execution)이나 메소드 콜(method call)과 같은 시스템의 실행을 포인트로 지정하는 것이다.
@jigi-kim Java에는를 확장한 AspectJ가 있는데요. 문법이 다르지만 언어에 종속적이기 때문에 어떻게 보면 확장 라이브러리나 익스텐션이라고 생각할 수도 있겠습니다. 
기본적으로 oop 언어를 지원하기 위한 패러다임이기 때문에 기존 언어를 구현하거나 라이브러리 형식으로 제공되는 것이 대부분인 것 같습니다. https://en.wikipedia.org/wiki/Aspect-oriented_programming#Implementations
이처럼 언어에 종속적인 이유는 작동원리가 작성 코드를 다시 컴파일하여 내부의 소스를 변환시키는 작업이 aop 컴파일러에서 일어나기 때문이라 생각되네요.

2020-12-15 01:44 UTC, Dae-Hwa commented on CS/aspect-oriented-programming.md
> + 	public void doSomething() {
@jigi-kim 적용했습니다.

2020-12-15 13:23 UTC, jigi-kim commented on CS/aspect-oriented-programming.md
> +aspect는 기존 프로그램의 동작과 관계없이 추가, 변경 가능해야 한다. 관점 지향 언어들은 기존 프로그램의 동작과 관계없이 실행 지점을 설정할 수 있도록 지원해주는데 이를 **join point**라고 한다. 메소드 실행(method execution)이나 메소드 콜(method call)과 같은 시스템의 실행을 포인트로 지정하는 것이다.
@Dae-Hwa 궁금했던 부분을 정확히 짚어주신 것 같네요. 자세한 설명 감사합니다. :)

2020-12-15 13:24 UTC, jigi-kim commented on CS/aspect-oriented-programming.md
> +위에서 본 개념들만 살펴봤을 때는 AOP가 구세주처럼 느껴질 수 있다. 하지만 AOP에도 문제 발생 가능성이 있다. AOP를 사용할 경우 아래 사항들을 인지한 뒤 도입해야 한다.
@Dae-Hwa 추후 작성하실 글을 기대하며... resolve 합니다.

2020-12-15 13:24 UTC, jigi-kim approved these changes

2020-12-15 19:35 UTC, dididy approved these changes

2020-12-15 19:37 UTC, merged