Cookie Store API
im-d-team/Dev-Docs pull request #195
Opened 2020-11-01 02:16 UTC by SeonHyungJo

2020-11-06 07:35 UTC, BKJang commented on Browser/Cookie_Store.md
> +`getAll`, `get`, `delete` 메서드를 사용하는 방법은 기본적으로 cookie의 이름만으로 사용할 수 있고, option이라는 것을 통해서 가져오거나 삭제가 가능한다. 자세한 형태는 아래를 살펴보면 된다.
```suggestion
`getAll`, `get`, `delete` 메서드를 사용하는 방법은 기본적으로 cookie의 이름만으로 사용할 수 있고, option이라는 것을 통해서 가져오거나 삭제가 가능하다. 자세한 형태는 아래를 살펴보면 된다.
```

2020-11-06 07:37 UTC, BKJang commented on Browser/Cookie_Store.md
> +이 부분의 차이점을 알고있는 것이 중요하다.
이 차이를 아는 것이 왜 중요한가요??

2020-11-06 07:39 UTC, BKJang commented on Browser/Cookie_Store.md
> +Cookie Store API는 HTTP 쿠키를 서비스 워커에서도 접근이 가능하며, `document.cookie`에서 비동기적으로 사용가능하도록 하는 기능이라고 명세가 되어있다.
제가 경험이 부족해서 그런지 Cookie Store API를 왜 사용해야하는지 잘 와 닿지 않아서 질문드립니다.
cookie을 비동기적으로 사용한다는게 무슨의미이고 장점이 뭐가 있을까요?

2020-11-06 07:40 UTC, BKJang requested changes
질문 답변 부탁드립니당 😄

2020-11-06 09:01 UTC, SeonHyungJo commented on Browser/Cookie_Store.md
> +이 부분의 차이점을 알고있는 것이 중요하다.
이전 글에서 언급해주신 부분이기도 한데 결국 이전의 방법으로 설정하는 것은 'lax'인데 난 외부에 공개를 아예하고 싶지 않은데 공개가 될 수 있으며, 또는 나는 어느정도 허용하고 싶은데 기본값이 'strict'로 설정이 되어버리면 결국 개발자가 원하는대로 cookie가 작동이 되지 않아서 각각의 기능을 사용할 때는 어떤 값이 기본값으로 설정이 되고 어떻게 설정이 되어야 내가 원하는대로 작동이 되는가를 알 수 있기에, 차이를 아는 것이 중요하다고 생각합니다.

2020-11-06 09:09 UTC, SeonHyungJo commented on Browser/Cookie_Store.md
> +Cookie Store API는 HTTP 쿠키를 서비스 워커에서도 접근이 가능하며, `document.cookie`에서 비동기적으로 사용가능하도록 하는 기능이라고 명세가 되어있다.
비동기적이라는 것은 결국 해당 API를 사용하는데 Promise를 반환한다는 의미가 됩니다. 그리고 그에 결과가 resolve와 reject로 나온다는 거죠. 

일단 여기서 좋은 점은 내가 실행한 API가 실제로 잘 작동했는지 또는 에러가 났는지 명확하게 알 수 있다는 것이 중요합니다. 이전에 cookie는 단순히 cookie에 맞는 string을 만들어서 넣는게 끝이니까요. 그리고 이게 성공인지 실패인지도 인지조차 불가능합니다.

또한 해당 API는 외부에 공개된 get, set, delete만을 사용하도록 하기 때문에 cookie의 값으로 어떤 것을 입력해야하는지 명확해집니다.

그리고 왜 사용해야하는지를 물어보시면 그건 개발자 자신의 몫이라고 생각합니다. 어느 기술이나 개발자가 필요성을 느끼면 사용하게 되는 것이고 필요없다고 생각하면 사용을 안하면 된다고 생각합니다. 새로운 기능, 기술이 나온다고 써야한다는 조건이 있는 건 아니니까요. 

또한 언급된 내용 중 이 API는 크롬만 가능한 API 입니다. 그래서 지금 당장은 저도 사용해야 하는 이유는 모르겠네요. @BKJang

2020-11-09 11:17 UTC, jigi-kim approved these changes

2020-11-23 15:29 UTC, BKJang commented on Browser/Cookie_Store.md
> +Cookie Store API는 HTTP 쿠키를 서비스 워커에서도 접근이 가능하며, `document.cookie`에서 비동기적으로 사용가능하도록 하는 기능이라고 명세가 되어있다.
```
일단 여기서 좋은 점은 내가 실행한 API가 실제로 잘 작동했는지 또는 에러가 났는지 명확하게 알 수 있다는 것이 중요합니다. 이전에 cookie는 단순히 cookie에 맞는 string을 만들어서 넣는게 끝이니까요. 그리고 이게 성공인지 실패인지도 인지조차 불가능합니다.

또한 해당 API는 외부에 공개된 get, set, delete만을 사용하도록 하기 때문에 cookie의 값으로 어떤 것을 입력해야하는지 명확해집니다.
```

명쾌했습니다. 감사합니다 👍

2020-11-23 15:29 UTC, BKJang approved these changes
답변 감사합니다. 승인할게요 👍

2020-12-05 15:30 UTC, JegalEun approved these changes
승인합니다~ 수고하셨어요

2020-12-09 05:24 UTC, EUNJIHA approved these changes
깔끔하게 정리되어 있어서 잘 읽힙니다. 승인합니다!

2020-12-09 05:25 UTC, merged