Web Storage API
im-d-team/Dev-Docs pull request #198
Opened 2020-11-22 04:58 UTC by dididy

2020-12-06 09:10 UTC, jigi-kim requested changes
문서 내용에 대한 질문 및 수정/확인 요청을 남깁니다.

2020-12-06 09:10 UTC, jigi-kim commented on Javascript/Web_Storage_API.md
> +Web Storage는 기본적으로 쿠키와 동일하게 오리진(domain/port/protocol)에 따라 값에 대한 접근이 제한된다. Local Storage의 경우 특정 오리진에 저장된 데이터가 있더라도 다른 오리진에서 접근할 수 없다. 오로지 오리진이 같이 야만 해당 데이터에 접근할 수 있다.
```suggestion
Web Storage는 기본적으로 쿠키와 동일하게 오리진(domain/port/protocol)에 따라 값에 대한 접근이 제한된다. Local Storage의 경우 특정 오리진에 저장된 데이터가 있더라도 다른 오리진에서 접근할 수 없다. 오로지 오리진이 같아야만 해당 데이터에 접근할 수 있다.
```

2020-12-06 09:10 UTC, jigi-kim commented on Javascript/Web_Storage_API.md
> +저장되면 영구적으로 데이터가 저장되면 Local Storage와 다르게 Session Storage는 브라우저를 닫는 등 세션이 종료되면 데이터가 삭제된다. Session Storage의 이러한 특성으로 인해 보안이 필요한 경우 사용하면 좋다.
```suggestion
저장되면 영구적으로 데이터가 저장되는 Local Storage와 다르게 Session Storage는 브라우저를 닫는 등 세션이 종료되면 데이터가 삭제된다. Session Storage의 이러한 특성으로 인해 보안이 필요한 경우 사용하면 좋다.
```

2020-12-06 09:10 UTC, jigi-kim commented on Javascript/Web_Storage_API.md
> +앞서 설명했듯이 Local Storage는 오리진 같다면 전역으로 데이터를 공유할 수 있었다. 하지만 Session Storage의 경우 오리진이 같더라도 서로 다른 탭 혹은 서로 다른 브라우저라면 서로의 데이터를 침범할 수 없다. 즉 Local Storage와 달리 해당 탭에 대해 종속되어 있게 된다.
```suggestion
앞서 설명했듯이 Local Storage는 오리진이 같다면 전역으로 데이터를 공유할 수 있었다. 하지만 Session Storage의 경우 오리진이 같더라도 서로 다른 탭 혹은 서로 다른 브라우저라면 서로의 데이터를 침범할 수 없다. 즉 Local Storage와 달리 해당 탭에 대해 종속되어 있게 된다.
```

2020-12-06 09:10 UTC, jigi-kim commented on Javascript/Web_Storage_API.md
> +```
설정하고자 하는 데이터와 동일한 `key` 값을 가진 데이터가 이미 저장되어 있다면 `value` 값이 교체가 되나요?

혹은, `removeItem()`을 통해 기존 데이터를 제거한 후 다시 설정해주는 과정을 거쳐야 하나요?

2020-12-07 10:44 UTC, dididy commented on Javascript/Web_Storage_API.md
> +```
removeItem()을 거칠 필요 없이 값이 교체됩니다!

2020-12-07 10:46 UTC, dididy commented
@jigi-kim 반영하였습니다! 다음부터는 꼼꼼히 검토하고 푸시해야겠네요..

2020-12-07 16:34 UTC, jigi-kim commented on Javascript/Web_Storage_API.md
> +```
@dididy 답변 감사합니다. resolve 합니다.

2020-12-07 16:35 UTC, jigi-kim commented
> @jigi-kim 반영하였습니다! 다음부터는 꼼꼼히 검토하고 푸시해야겠네요..

작성자는 놓치기 쉬우니까요... 이게 review를 거치는 이유죠 :)

2020-12-07 16:35 UTC, jigi-kim approved these changes

2020-12-12 09:03 UTC, SeonHyungJo requested changes
간단하게 리뷰 남겼습니다. 확인부탁드립니다. 👍

2020-12-12 09:03 UTC, SeonHyungJo commented on Javascript/Web_Storage_API.md
> +- `oldValue` – 이전 값(키가 새롭게 추가되었다면 창null`)
```suggestion
- `oldValue` – 이전 값(키가 새롭게 추가되었다면 창 `null`)
```

백틱이 하나가 부족합니다. 수정부탁드립니다.

2020-12-12 09:03 UTC, SeonHyungJo commented on Javascript/Web_Storage_API.md
> +Web Storage을 잘 응용한 사례는 다음과 같은 경우가 있을 수 있다.
```suggestion
Web Storage을 잘 응용한 사례는 다음과 같은 경우가 있다.
```

다른 사람들이 보는 글에서 `있을 수 있다.`는 식의 말은 안쓰는게 개인적으로는 안 좋다고 생각합니다.

2020-12-14 03:00 UTC, BKJang approved these changes
다른 분들이 이미 리뷰를 많이 해주셨네요. 오랜만에 복습하는 느낌으로 글을 읽으니까 또 새롭네요ㅎㅎ
고생하셨습니다. 👍

2020-12-15 19:09 UTC, dididy commented on Javascript/Web_Storage_API.md
> +개발을 진행하다가 클라이언트에서 특정 값을 저장해야 하는 기능 구현 필요성이 생겼다면 어떻게 해야 할까? 쿠키를 사용할 경우 제약 사항이 생길 수 있다. Web Storage API를 사용하게 되면 앞서 의도한 목적에 맞게 기능을 구현할 수 있다.
`생성할 수 있는 개수 및 데이터 크기 등의 제약사항을이 생길 수 있다.` 로 수정하여 반영하였습니다!

2020-12-15 19:12 UTC, dididy commented on Javascript/Web_Storage_API.md
> +쿠키의 경우 서버와 효율적으로 통신하기 위한 배경으로 탄생했다. 실제로 쿠키는 HTTP 헤더를 바탕으로 서버와 클라이언트가 서로를 식별하는 인증 과정을 위해 가장 많이 사용된다.
동의합니다. 반영하였습니다!

2020-12-15 19:15 UTC, dididy commented on Javascript/Web_Storage_API.md
> +- `oldValue` – 이전 값(키가 새롭게 추가되었다면 창null`)
반영하였습니다!

2020-12-15 19:17 UTC, dididy commented on Javascript/Web_Storage_API.md
> +Web Storage을 잘 응용한 사례는 다음과 같은 경우가 있을 수 있다.
반영하였습니다!

2020-12-20 04:07 UTC, Dae-Hwa approved these changes
승인합니다!

2020-12-20 06:58 UTC, SeonHyungJo approved these changes
승인합니다.

2020-12-20 06:59 UTC, merged