React Component, Props, States
im-d-team/Dev-Docs pull request #199
Opened 2020-11-22 05:08 UTC by EUNJIHA

2020-12-12 09:15 UTC, SeonHyungJo requested changes
오랜만에 React를 보니 반갑네요. 맨날 Vue만 봐왔었는데... 😢 😢 😢 

리뷰내용 확인부탁드립니다.

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +React는 `Component`개념에 집중 되어 있는 라이브러리다. `Component`는 JavaScript의 함수와 유사하다고 할 수 있는데, `Props`라는 데이터를 입력 받고 화면에 표시될 React `Element`를 반환한다. 한마디로 재사용 가능한 UI 조각이라고 생각하면 된다.
```suggestion
React는 `Component`개념에 집중되어 있는 라이브러리다. `Component`는 JavaScript의 함수와 유사하다고 할 수 있는데, `Props`라는 데이터를 입력 받고 화면에 표시될 React `Element`를 반환한다. 한마디로 **재사용 가능한 UI 조각**이라고 생각하면 된다.
```

띄어쓰기와 강조되었으면 하는 부분을 작성해보았습니다.

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +cf. React Component 이름은 다음 `Welcome`과 같이 항상 **대문자**로 시작한다.
대문자로 시작해야하는 이유가 있을까요? @EUNJIHA

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +React Component 에는 `Function Component`와 `Class Component`가 있다. 이  Component들의 가장 큰 차이점은 `LifeCycle`과 `State`이다. (추후에 다룰 예정)
```suggestion
React Component 에는 `Function Component`와 `Class Component`가 있다. 이 Component들의 가장 큰 차이점은 `LifeCycle`과 `State`이다. (추후에 다룰 예정)
```

띄어쓰기 수정요청드립니다.

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +	// const [content, setContent] = useState("");
```suggestion
    // const [content, setContent] = useState("");
```

이 부분이 지금 필요할까요? 주석처리된 것을 봐서는 필요없어보이는데요

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +다음 `Comment` Component에는 유저사진 / 유저이름 / 내용 / 날짜 가 브라우저 DOM 태그 형태 그대로 포함되어 있다.
```suggestion
다음 `Comment` Component에는 유저사진 / 유저이름 / 내용 / 날짜가 브라우저 DOM 태그 형태 그대로 포함되어 있다. 
```

수정요청드립니다.

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +전체 코드는 다음과 같다. // 배열도 구조분해 할당 쓸 수 있는데, 개수가 명확할 때만 쓴다.
```suggestion
전체 코드는 다음과 같다. // 배열도 구조분해 할당 쓸 수 있는데, 개수가 명확할 때만 쓴다. 
```

여기서 주석처리를 하신건가요?? 이유가 있을까요?

2020-12-12 09:15 UTC, SeonHyungJo commented on React/Component, Props, State.md
> +> `순수함수` 란 입력 값을 바꾸지 않는 함수이다. 동일한 입력값에 대해서 항상 동일한 결과를 반환한다.
순수함수라는 어려운 것을 건들여 주셔서 기분이 좋네요. 시간이 되실 때 깊게 찾아보시면 좋습니다.

2020-12-14 03:02 UTC, BKJang commented on React/Component, Props, State.md
> +추출은 할 일이 많아보이지만 컴포넌트를 재사용할 일이 많은 App 에서는 유지 보수가 더 수월해진다. 1) UI 일부가 여러 번 사용되거나(Button, Panel, Avatar) 2) UI 일부가 자체적으로 복잡한 경우에는(App, FeedStory, Comment) 별도의 컴포넌트로 만드는 게 좋다.
```suggestion
추출을 사용하면 컴포넌트를 재사용할 일이 많은 App 에서는 유지 보수가 더 수월해진다. 1) UI 일부가 여러 번 사용되거나(Button, Panel, Avatar) 2) UI 일부가 자체적으로 복잡한 경우에는(App, FeedStory, Comment) 별도의 컴포넌트로 만드는 게 좋다. 
```

2020-12-14 03:04 UTC, BKJang commented on React/Component, Props, State.md
> +> `순수함수` 란 입력 값을 바꾸지 않는 함수이다. 동일한 입력값에 대해서 항상 동일한 결과를 반환한다.
React는 함수형 프로그래밍을 기반하고 있고 함수형 프로그래밍의 요소 중 하나가 '순수함수'입니다.
순수함수를 찾아보시고 이해가 가시면 함수형 프로그래밍부터 다시 한 번 보면 더 좋을 것 같네요 😄

2020-12-14 03:04 UTC, BKJang commented on React/Component, Props, State.md
> +	//
```suggestion
```

2020-12-14 03:07 UTC, BKJang commented on React/Component, Props, State.md
> +### (2) State 업데이트는 비동기적일 수도 있다. // 스레드 safe하지 않다
```suggestion
### (2) State 업데이트는 비동기적일 수도 있다.
```
쓰레드 safe하지 않다는 것은 비동기적으로 동작한다는 의미가 아닙니다.

작업들이 비동기적으로 동작할 때, 동기적으로 동작하도록 해줘야하고 그런 경우 `async-await`나 Generator의 `yield` 구문을 사용하곤 합니다.

쓰레드 safe하지 않다는 것은 쉽게 말하면 side-effect에 가깝구요. 즉, 일어나서는 안되는 경우라고 보는게 맞을 것 같습니다.
따라서 해당 주석은 지워주는게 낫겠네요ㅎㅎ

2020-12-14 03:08 UTC, BKJang requested changes
몇 가지 커멘트 남겼구요.
소스 내에서 필요 없는 주석은 지워주는게 나을 것 같아요.
React를 공부하면서 JS도 같이 공부하면 더 좋을 것 같습니다 😄

2020-12-21 06:30 UTC, Dae-Hwa requested changes
전체적으로 주석처리 된 부분에 알 수 없는 의미가 많은 것 같아요.
들여쓰기도 함께 전체적으로 확인해주시면 좋겠습니다.

2020-12-21 06:30 UTC, Dae-Hwa commented on React/Component, Props, State.md
> +  return <h1>Hello, {props.name}</h1>; //
내용이 없는 주석이네요

2020-12-21 06:30 UTC, Dae-Hwa commented on React/Component, Props, State.md
> +### (1) JavaScript 함수로 작성: `Function Component` //16버전?부터?
`//` 뒷 내용은 주석으로 남겨놓으려고 했던 것인가요?

2020-12-21 06:30 UTC, Dae-Hwa commented on React/Component, Props, State.md
> +	// constructor(props) {
```suggestion
  // constructor(props) {
```

2020-12-21 06:30 UTC, Dae-Hwa commented on React/Component, Props, State.md
> +}
들여쓰기 확인 부탁드려요

2020-12-21 13:36 UTC, JegalEun requested changes

2020-12-21 13:36 UTC, JegalEun commented on React/Component, Props, State.md
> +```
주석이 만약 부가적인 설명(?)이였다면 따로 글로 적는게 더 좋을 것 같아요!!

2020-12-21 13:41 UTC, JegalEun requested changes

2020-12-21 13:41 UTC, JegalEun commented on React/Component, Props, State.md
> +> `순수함수` 란 입력 값을 바꾸지 않는 함수이다. 동일한 입력값에 대해서 항상 동일한 결과를 반환한다.
다음 주제는 순수함수로 발표해주세요~! ㅎㅎ

2020-12-22 08:12 UTC, EUNJIHA commented on React/Component, Props, State.md
> +cf. React Component 이름은 다음 `Welcome`과 같이 항상 **대문자**로 시작한다.
JSX에서 소문자 태그 이름은 HTML 태그로 간주되기 때문에 대문자로 작성해주어야 합니다.

2020-12-22 11:13 UTC, EUNJIHA commented on React/Component, Props, State.md
> +	// const [content, setContent] = useState("");
function 컴포넌트와 class 컴포넌트에서 상태를 어떻게 처리하는지 비교하기 위한 부분입니다. 조금 더 상세하게 수정했는데 확인부탁드립니다

2020-12-22 11:14 UTC, EUNJIHA commented on React/Component, Props, State.md
> +전체 코드는 다음과 같다. // 배열도 구조분해 할당 쓸 수 있는데, 개수가 명확할 때만 쓴다.
기록을 위해 작성했었는데, 삭제했습니다. 확인부탁드려요~

2020-12-22 11:14 UTC, EUNJIHA commented on React/Component, Props, State.md
> +> `순수함수` 란 입력 값을 바꾸지 않는 함수이다. 동일한 입력값에 대해서 항상 동일한 결과를 반환한다.
참고해보겠습니다. 감사합니다!

2020-12-22 11:16 UTC, EUNJIHA commented on React/Component, Props, State.md
> +### (2) State 업데이트는 비동기적일 수도 있다. // 스레드 safe하지 않다
상세한 설명 감사합니다! 이해 되었습니다

2020-12-22 11:16 UTC, EUNJIHA commented on React/Component, Props, State.md
> +  return <h1>Hello, {props.name}</h1>; //
삭제하였습니다

2020-12-22 11:16 UTC, EUNJIHA commented on React/Component, Props, State.md
> +### (1) JavaScript 함수로 작성: `Function Component` //16버전?부터?
이 부분도 기록을 위해 작성되었는데, 삭제되었습니다 확인부탁드려요!

2020-12-22 11:17 UTC, EUNJIHA commented on React/Component, Props, State.md
> +}
수정했습니다

2020-12-22 11:17 UTC, EUNJIHA commented on React/Component, Props, State.md
> +```
수정했습니다

2020-12-22 11:44 UTC, dididy requested changes
React라 재미있었네요. 몇가지 수정 요청 남겼습니다~

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +const secondElement = <Welcome name="Sara"/>; // 어떤 것이든 넘어가긴 함
`어떤 것이든 넘어가긴 함` 이라는 주석은 props에 대한 것인가요?

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +// const {author, } = props
이 주석의 의도는 무엇인가요?

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +`<MyName name = "은지">` 대신 `<MyName />` 과 같이 사용하면 위의 defaultProps인 '기본이름'을 name 으로 인식하게 된다.
Default Props를 다루는 김에 [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html)에 대한 설명도 있으면 좋을 것 같아요!

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +  render() {
```suggestion
  // (2) <Clock />의 constructor가 호출된다. state도 초기화한다.
  constructor(props) { 
    super(props);
    this.state = {date: new Date()};
  }

  // (4) (3)이 처음 실행된 직후 componentDidMount() 생명주기 메서드가 실행된다. 
  componentDidMount() {
    this.timerID = setInterval(
      () => this.tick(),
      1000
    );
  }
	

  // (6) <Clock />이 DOM에서 삭제되었다면 componentWillUnmount() 생명주기 메서드가 실행된다.
  componentWillUnmount() {
    clearInterval(this.timerID);
  }

  // (5) setState() 메서드가 있으므로 새로운 state로 render() 메소드를 다시 호출한다. (this.state ~ 로 직접 수정하는게 아니다!)
  tick() {
    this.setState({
      date: new Date()
    });
  }

  // (3) <Clock />의 render() 메서드를 호출한다. 화면에 표시할 내용이다. (2)에서 초기화된 state를 기반으로 화면에 Mount한다.
  render() {
```

이런식으로 주석 탭 컨벤션을 맞추면 보기 편할 것 같아요!

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +})
```suggestion
    return { 
     counter: state.counter + props.increment;
    }
  })
```
이부분도 탭 컨벤션을 맞추면 좋을 것 같습니다!

2020-12-22 11:44 UTC, dididy commented on React/Component, Props, State.md
> +	return {...account, total: account.total - amount}
```suggestion
	return { ...account, total: account.total - amount }
```
이부분도 다른 코드들과 컨벤션을 맞춘다면 이렇게 수정하면 좋을 것 같습니다~

2020-12-23 12:04 UTC, BKJang approved these changes
승인합니다~ 고생하셨어요ㅎㅎ

2020-12-23 14:10 UTC, Dae-Hwa approved these changes

2020-12-25 03:32 UTC, SeonHyungJo approved these changes
승인합니다 👍

2021-01-02 07:18 UTC, JegalEun approved these changes
승인하겠습니다~

2021-01-05 03:42 UTC, dididy commented on React/Component, Props, State.md
> +// const {author, } = props
@EUNJIHA Prop-Types는 나중에 다뤄주시고 주석 두개만 제거해주시면 승인하겠습니다~

2021-01-05 03:50 UTC, EUNJIHA commented on React/Component, Props, State.md
> +// const {author, } = props
@dididy 이전에 수정 했는데 혹시 안보이실까요?

2021-01-05 03:51 UTC, dididy commented on React/Component, Props, State.md
> +// const {author, } = props
@EUNJIHA 수정이 안되어있는 것 같아요..!
<img width="805" alt="Screen Shot 2021-01-05 at 12 51 45 PM" src="https://user-images.githubusercontent.com/16266103/103604556-c53eb380-4f54-11eb-9395-1ceaa712f88b.png">

2021-01-05 04:01 UTC, EUNJIHA commented on React/Component, Props, State.md
> +// const {author, } = props
밑 부분 주석을 삭제하지 않았군요 방금 수정했습니다! @dididy

2021-01-05 04:07 UTC, dididy approved these changes
수고 많으셨어요. 승인힙니다!

2021-01-05 04:08 UTC, merged