JSPmodel
im-d-team/Dev-Docs pull request #200
Opened 2020-11-22 07:18 UTC by JegalEun

2020-12-06 09:01 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2020-12-14 03:09 UTC, BKJang commented on Design_Pattern/JSP model.md
> +웹 어플리케이션의 디자인에는 일반적으로 두 가지의 디자인 모델이 있다.
애플리케이션으로 하시죠

2020-12-14 03:09 UTC, BKJang commented on Design_Pattern/JSP model.md
> +잘못된 개념을 바로 잡아준 @Dae-Hwa 님께 감사합니다 :)
@Dae-Hwa ㅋㅋㅋㅋ

2020-12-14 03:10 UTC, BKJang approved these changes
깔끔하네요ㅎㅎ
점점 발전하고 있는 것 같아서 보기 좋아요
승인합니다 👍

2020-12-15 01:55 UTC, Dae-Hwa commented on Design_Pattern/JSP model.md
> +웹 어플리케이션의 디자인에는 일반적으로 두 가지의 디자인 모델이 있다.
@jigi-kim 
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=156784&pageIndex=1
애플리케이션이 바른 표기법인가봐요

2020-12-15 02:01 UTC, Dae-Hwa approved these changes
엄청난 피드백 감사합니다! ㅋㅋ
서블릿이 컴파일되는 부분은 was에 대해 살펴보시면 이해에 도움이 될 것 같아요.
승인합니다

2020-12-20 07:00 UTC, SeonHyungJo approved these changes
나날이 발전하는 모습이 좋습니다. 승인합니다. 👍

2020-12-20 14:48 UTC, dididy approved these changes

2020-12-21 14:03 UTC, JegalEun commented on Design_Pattern/JSP model.md
> +웹 어플리케이션의 디자인에는 일반적으로 두 가지의 디자인 모델이 있다.
애플리케이션으로 통일했습니다~

2020-12-21 14:11 UTC, jigi-kim approved these changes

2020-12-21 14:12 UTC, merged