정수 표현
im-d-team/Dev-Docs pull request #201
Opened 2020-11-23 02:03 UTC by Dae-Hwa

2020-12-06 08:58 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2020-12-06 08:58 UTC, jigi-kim commented on CS/integer_representation.md
> +보수 보충을 해주는 수를 의미한다. 예를 들어 1에 대한 10의 보수는 9(10 - 9), 4에 대한 15의 보수는 11(15 - 4)이 되는 것이다. 2진수에서는 1의 보수와 2의 보수를 사용할 수 있다. 컴퓨터는 이 중 2의 보수를 이용하여 음수를 나타낸다.
```suggestion
보수는 보충을 해주는 수를 의미한다. 예를 들어 1에 대한 10의 보수는 9(10 - 1), 4에 대한 15의 보수는 11(15 - 4)이 되는 것이다. 2진수에서는 1의 보수와 2의 보수를 사용할 수 있다. 컴퓨터는 이 중 2의 보수를 이용하여 음수를 나타낸다.
```

2020-12-09 05:46 UTC, EUNJIHA approved these changes
잠깐 잊고 있던 개념을 다시 볼 수 있어서 좋았습니다. 스터디 때 칠판에 자세하게 설명해주셔서 바로 이해가 잘 됩니다~

2020-12-15 01:17 UTC, Dae-Hwa commented on CS/integer_representation.md
> +보수 보충을 해주는 수를 의미한다. 예를 들어 1에 대한 10의 보수는 9(10 - 9), 4에 대한 15의 보수는 11(15 - 4)이 되는 것이다. 2진수에서는 1의 보수와 2의 보수를 사용할 수 있다. 컴퓨터는 이 중 2의 보수를 이용하여 음수를 나타낸다.
@jigi-kim 보수 틀린건 집어주시지 않았으면 눈치 못챌 뻔 했네요 감사합니다!

2020-12-15 03:22 UTC, jigi-kim approved these changes

2020-12-22 09:08 UTC, dididy requested changes
찬찬히 정독해보았는데 다시봐도 내용이 좋네요!

2020-12-22 09:08 UTC, dididy commented on CS/integer_representation.md
> +>   그림출처 : [정보통신기술용어해석](http://ktword.co.kr/abbr_view.php?nav=2&id=122&m_temp1=5048)
<img width="401" alt="Screen Shot 2020-12-22 at 6 05 03 PM" src="https://user-images.githubusercontent.com/16266103/102870318-3889f500-4480-11eb-9da6-785caf351ca0.png">

```suggestion
>   그림 출처 : [정보통신기술용어해석](http://ktword.co.kr/abbr_view.php?nav=2&id=122&m_temp1=5048)
```

요렇게 수정하면 좋을 것 같아요!

2020-12-22 13:04 UTC, Dae-Hwa commented on CS/integer_representation.md
> +>   그림출처 : [정보통신기술용어해석](http://ktword.co.kr/abbr_view.php?nav=2&id=122&m_temp1=5048)
@dididy 반영했습니다!

2020-12-22 13:11 UTC, dididy approved these changes

2020-12-25 03:34 UTC, SeonHyungJo approved these changes
질문들은 발표하실 때 다 한거 같습니다. 고생하셨습니다👍

2020-12-25 03:34 UTC, merged