Package Manager
im-d-team/Dev-Docs pull request #202
Opened 2020-12-27 05:26 UTC by EUNJIHA

2020-12-28 10:39 UTC, BKJang commented on Tool/Package Manager.md
> +<img width="719" alt="Comparison of conda and" src="https://user-images.githubusercontent.com/43839938/103164402-2c21e580-484e-11eb-9892-320d23658459.png">
```suggestion
![Comparison of conda and](https://user-images.githubusercontent.com/43839938/103164402-2c21e580-484e-11eb-9892-320d23658459.png)
```

2020-12-28 10:40 UTC, BKJang commented on Tool/Package Manager.md
> +또 하나의 핵심 차이는 두 개 모두 각 프로젝트 단위로 라이브러리를 설치하도록 하는 '가상환경' 을 사용할 수 있지만 접근 방식이 조금 다르다는 점이다. conda의 경우 '가상환경'이 내장되어 있지만, pip는 virtualenv등을 따로 설치해서 사용해야 한다.
각 프로젝트 단위로 라이브러리를 설치하도록 하는 '가상환경' 을 사용할 수 있다는 것의 의미를 잘 모르겠는데 좀 더 자세히 설명해주실 수 있나요?

2020-12-28 10:42 UTC, BKJang commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
ㅋㅋㅋㅋㅋㅋ 파이팅!

2020-12-28 10:43 UTC, BKJang requested changes
간략하게 각 Package Manager들에 대한 소개로 괜찮은 글 같습니다.
고생하셨어요ㅎㅎ
커멘트 확인하고 피드백 부탁드려요 🙏

2020-12-28 12:17 UTC, dididy requested changes
발표 재미있게 잘 들었습니다! 수고 많으셨어요~

2020-12-28 12:17 UTC, dididy commented on Tool/Package Manager.md
> +pip, conda는 Python에서 사용할 수 있는 Package Managers이다. 이 둘은 비슷한 개념으로 많이 사용되는데 명확하게는 서로 다른 목적을 가지고 있다. 다음 표를 살펴보자. 자세한 설명은 [이곳](https://www.anaconda.com/blog/understanding-conda-and-pip)을 참고하면 된다.
```suggestion
pip, conda는 Python에서 사용할 수 있는 Package Manager이다. 이 둘은 비슷한 개념으로 많이 사용되는데 명확하게는 서로 다른 목적을 가지고 있다. 다음 표를 살펴보자. 자세한 설명은 [이곳](https://www.anaconda.com/blog/understanding-conda-and-pip)을 참고하면 된다.
```
Managers는 오타인 것 같습니다

2020-12-28 12:17 UTC, dididy commented on Tool/Package Manager.md
> +`conda`와 `pip`를 결합해서 사용하는 경우도 존재한다. `conda` 의 Repository인 [Anaconda](https://www.anaconda.com/)에서는 데이터 과학, 기계 학습 등 AI 프레임워크를 포함한 1,500개 이상의 패키지를 제공하기 때문에 `conda`를 사용한다. 그럼에도 `pip`와 결합해서 사용하는 이유는 Anac
이런식의 사용법은 conda의 가상환경에 pip를 이용해 conda의 Repository에 없는 패키지를 설치하는 형태가 되는걸까요?

2020-12-28 12:17 UTC, dididy commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
```suggestion
 Java의 Package Manager는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Gradle` 공식 사이트에 이 둘에 대한 차이점이 잘 설명되어 있다. [이곳](https://gradle.org/maven-vs-gradle/)을 참고하자. `Maven`과 비교했을 때 `Gradle`의 대표적인 장점은 다음과 같다.
```
여기서도 Managers는 오타인 것 같습니다.

2020-12-28 12:17 UTC, dididy commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
혹시 Maven만의 장점은 없나요? 단지 레거시이기때문에 사용하는 느낌일까요?

2020-12-28 12:17 UTC, dididy commented on Tool/Package Manager.md
> +    ```xml
```suggestion
```xml
```
렌더링에는 영향이 없는 것 같긴 한데 불필요한 탭이 들어간 것 같아요!

2020-12-29 14:02 UTC, SeonHyungJo requested changes
리뷰 남겼습니다.

2020-12-29 14:02 UTC, SeonHyungJo commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
@EUNJIHA Gradle의 불편한 점은 없나요?

2020-12-29 14:02 UTC, SeonHyungJo commented on Tool/Package Manager.md
> +**Manager**: `npm`
yarn이 없어서 아쉽네요 😢

2020-12-29 14:02 UTC, SeonHyungJo commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
@EUNJIHA 파이팅!

2021-01-02 07:26 UTC, JegalEun requested changes

2021-01-02 07:26 UTC, JegalEun commented on Tool/Package Manager.md
> +`conda`와 `pip`를 결합해서 사용하는 경우도 존재한다. `conda` 의 Repository인 [Anaconda](https://www.anaconda.com/)에서는 데이터 과학, 기계 학습 등 AI 프레임워크를 포함한 1,500개 이상의 패키지를 제공하기 때문에 `conda`를 사용한다. 그럼에도 `pip`와 결합해서 사용하는 이유는 Anac
Anaconda에 없는 패키지가 Pypi에서 있기때문에 결합한다고 하셨는데, Pypi를 사용하면 안되는 걸까요? 굳이 결합해서 쓰는 이유가 궁금합니다!

2021-01-02 07:31 UTC, JegalEun requested changes

2021-01-02 07:31 UTC, JegalEun commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
Maven의 어떤 단점을 보완한 것인지 궁금합니다!

2021-01-02 07:34 UTC, JegalEun requested changes

2021-01-02 07:34 UTC, JegalEun commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
파이팅!! ㅋㅋㅋ

2021-01-02 07:34 UTC, JegalEun commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
파이팅!ㅋㅋ

2021-01-08 18:13 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2021-01-08 18:13 UTC, jigi-kim commented on Tool/Package Manager.md
> +<img width="719" alt="Comparison of conda and" src="https://user-images.githubusercontent.com/43839938/103164402-2c21e580-484e-11eb-9892-320d23658459.png">
위 비교 표는 conda의 강점을 보여주기 위한 용도로 conda에서 만든 것이다 보니, 두 언어의 특징을 좀 더 객관적으로 보여주지는 못하는 것 같네요.

수정 요청을 하는 부분은 아니지만, 다양한 경로로 두 패키지에 대한 특징들이 조사되었으면 더 좋지 않았을까 하는 생각이 듭니다. :)

2021-01-08 18:13 UTC, jigi-kim commented on Tool/Package Manager.md
> +    ```groovy
```suggestion
2) `Gradle`의 build.gradle 예시 - `Gradle`역시 `Maven Central`을 레포지토리로 한다.

```groovy
```
2번 항목에 들여쓰기가 적용되면서 1번 항목의 소항목처럼 렌더링되네요. 위 @BKJang comment와 마찬가지로 들여쓰기 제거가 필요해 보입니다.

2021-01-08 18:13 UTC, jigi-kim commented on Tool/Package Manager.md
> + Java의 Repository(Maven Central)에는 개인이 만든 Package를 추가하는 과정이 [복잡하다](https://jojoldu.tistory.com/161). 따라서 Nexus와 같은 사설 Repository를 [사용하기도](https://dev-youngjun.tistory.com/105) 한다.
이 부분은 `2. 빌드 시 속도가 더 빠르다.`의 설명 내용인가요? 개발/배포 과정의 편의성에 더 가까워 보이는데, 3번 항목으로 표시되거나 2번 항목과 구분 지을 방법이 필요해 보입니다.

2021-01-08 18:13 UTC, jigi-kim commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
다른 사람들이 함께 파이팅을 외쳐준다는 것, 얼마나 아름다운가?

@im-d-team 파이팅!

2021-01-08 18:13 UTC, jigi-kim commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
```suggestion
종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들이 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀 줄 것이다. 파이팅!
```

2021-01-09 06:31 UTC, BKJang approved these changes
질문 답변만 해주시면 되겠네요 😁 먼저 승인할게요 고생하셨습니다👍

2021-01-09 06:53 UTC, EUNJIHA commented on Tool/Package Manager.md
> +종속성, 패키지 이름, 작성자, 태그 / 키워드 및 버전 번호 등을 지정해서 Package를 만들고 Repository에 등록해보자. 다른 사람들은 여러분들의 라이브러리를 사용한다는 것, 얼마나 아름다운가? 이로써 개발자는 Package를 사용하고 구현하는 방법에 대해 생각할 수 있고 더 나은 재사용 가능한 Package를 생성할 수 있도록 생각을 넓혀
👍🏼

2021-01-09 08:11 UTC, EUNJIHA commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
@dididy 아무래도 Maven이 Gradle보다 오래되었기 때문에 사용자 경험 측면에서는 Maven 쪽이 우세합니다. [참고](https://yeti.tistory.com/231) 

@SeonHyungJo Gradle의 불편한 점은 Groovy라는 새로운 형태를 익혀야 한다는 것이 큰 거 같습니다.

2021-01-09 08:11 UTC, EUNJIHA commented on Tool/Package Manager.md
> + Java의 Package Managers는(Build Tool이라고도 불린다.) [`Maven`](https://maven.apache.org/), [`Gradle`](https://gradle.org/)이 있다. `Maven`은 pom.xml을 이용한 정형화된 빌드 시스템이다. `Gradle`은 `Maven`의 단점을 보완하고자 나온 것인데 `Grad
1. 멀티 프로젝트에서 특정 설정을 다른 모듈에서 사용하려면 상속을 받아야 한다. -> Gradle은 설정 주입 방식을 통해 이를 해결한다. 
2. XML 의 난해한 코드 가독성 -> Gradle의 Groovy 문법을 통해 좀 더 간결하게 작성 가능하다.

등이 있습니다.

2021-01-09 08:11 UTC, EUNJIHA commented on Tool/Package Manager.md
> + Java의 Repository(Maven Central)에는 개인이 만든 Package를 추가하는 과정이 [복잡하다](https://jojoldu.tistory.com/161). 따라서 Nexus와 같은 사설 Repository를 [사용하기도](https://dev-youngjun.tistory.com/105) 한다.
2번과 별개의 구성입니다. 수정하겠습니다

2021-01-09 08:11 UTC, EUNJIHA commented on Tool/Package Manager.md
> +**Manager**: `npm`
간단하게 추가해봤습니다.

2021-01-09 08:12 UTC, EUNJIHA commented on Tool/Package Manager.md
> +<img width="719" alt="Comparison of conda and" src="https://user-images.githubusercontent.com/43839938/103164402-2c21e580-484e-11eb-9892-320d23658459.png">
넵 무슨 말씀이신지 이해되었습니다!

2021-01-09 09:00 UTC, jigi-kim approved these changes

2021-01-11 14:14 UTC, dididy approved these changes
승인합니다!

2021-01-12 01:43 UTC, SeonHyungJo commented on Tool/Package Manager.md
> +또 하나의 핵심 차이는 두 개 모두 각 프로젝트 단위로 라이브러리를 설치하도록 하는 '가상환경' 을 사용할 수 있지만 접근 방식이 조금 다르다는 점이다. conda의 경우 '가상환경'이 내장되어 있지만, pip는 virtualenv등을 따로 설치해서 사용해야 한다.
아 그런거군요 이해됐습니다.

2021-01-12 01:44 UTC, SeonHyungJo approved these changes
수고하셨습니다. 승인합니다.

2021-01-12 12:14 UTC, JegalEun approved these changes
승인하겠습니다 :)

2021-01-12 12:15 UTC, merged