methods_in_IPC
im-d-team/Dev-Docs pull request #203
Opened 2021-01-03 03:47 UTC by Dae-Hwa

2021-01-03 08:31 UTC, BKJang commented on CS/methods_in_IPC.md
> +
장점과 맞춰서 공백 제거하면 좋을듯 합니다.

2021-01-03 08:33 UTC, BKJang commented on CS/methods_in_IPC.md
> +key를 이용한 큐 방식이다. 선입선출 외에 지정한 key 중 가장 먼저 입력된 자료를 꺼낼 수 있다. 양방향으로 통신할 수 있다.![메세지큐1.png](https://github.com/Dae-Hwa/diagrams/blob/master/os/ipc/%EB%A9%94%EC%84%B8%EC%A7%80%ED%81%901.png?raw=true)
선입선출 외에 지정한 key 중 가장 먼저 입력된 자료를 꺼낼 수 있다는 것이 무슨 의미인지 잘 이해가 안가는데, 선출 과정에서 key값을 우선적으로 참조한다는 것인가요?

2021-01-03 08:33 UTC, BKJang commented on CS/methods_in_IPC.md
> +
공백(줄바꿈) 제거가 좋을듯 합니다.

2021-01-03 08:33 UTC, BKJang commented on CS/methods_in_IPC.md
> +커널 또는 프로세스에서 다른 프로세스에 어떤 이벤트가 발생했는지 알려주는 기법이다. 프로세스의 실행 종료 등을 알려준다. 프로세스에서 시그널을 재정의하면 시그널의 기본 동작과 다른 동작을 할 수 있다. 이를 이용하기 위해 유저 정의 시그널(리눅스의 경우 SIGUSR1, 2)를 제공한다.
```suggestion
커널 또는 프로세스에서 다른 프로세스에 어떤 이벤트가 발생했는지 알려주는 기법이다. 프로세스의 실행 종료 등을 알려준다. 프로세스에서 시그널을 재정의하면 시그널의 기본 동작과 다른 동작을 할 수 있다. 이를 이용하기 위해 유저 정의 시그널(리눅스의 경우 SIGUSR1, 2)을 제공한다.
```

2021-01-03 08:34 UTC, BKJang commented on CS/methods_in_IPC.md
> +시그널의 좀 더 자세한 동작 원리는 인터럽트가 종료되어 사용자 모드로 전환하는 시점에 pcb(process control block)에 있는 시그널과 관련된 자료구조의 상태를 확인하는 것이다. 이를 이용하여 다른 IPC 기법과 조합하여 사용할 수 있다. 데이터를 직접 전송할 수 없다는 단점이 있다.
시그널과 관련된 자료구조의 상태를 확인한다는 것이 뭔가요? 해당 자료구조는 어떤 형태를 띄고 있나요?

2021-01-03 08:35 UTC, BKJang commented on CS/methods_in_IPC.md
> +
줄바꿈을 제거하든지 다 넣든지 통일이 되어야 할듯 하네요 😂

2021-01-03 08:37 UTC, BKJang requested changes
수정 사항은 많이 없구 질문을 같이 남겼습니다. 피드백 부탁드려요ㅎㅎ
아무래도 지난 OS 시간에 들은 것을 복스하는 느낌이라 이해가 쉬웠던 것 같은데 막상 읽으니 이해가 안되는 부분이 있네요 😅
재밌는 발표였습니다~

2021-01-03 11:32 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +시그널의 좀 더 자세한 동작 원리는 인터럽트가 종료되어 사용자 모드로 전환하는 시점에 pcb(process control block)에 있는 시그널과 관련된 자료구조의 상태를 확인하는 것이다. 이를 이용하여 다른 IPC 기법과 조합하여 사용할 수 있다. 데이터를 직접 전송할 수 없다는 단점이 있다.
pending 상태인지 블록상태인지 핸들러를 수행해야 하는지 등의 상태를 가진 자료구조들이 들어있는 겁니다.
자세한 구조는 https://github.com/torvalds/linux/blob/master/include/linux/sched/signal.h#L82:1 여기를 한 번 살펴보면 될 것같은데 저는 아직 마음의 준비가 안 된것 같습니다...ㅋㅋㅋ

2021-01-03 11:34 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +key를 이용한 큐 방식이다. 선입선출 외에 지정한 key 중 가장 먼저 입력된 자료를 꺼낼 수 있다. 양방향으로 통신할 수 있다.![메세지큐1.png](https://github.com/Dae-Hwa/diagrams/blob/master/os/ipc/%EB%A9%94%EC%84%B8%EC%A7%80%ED%81%901.png?raw=true)
@BKJang 네 맞습니다. A B C 가 있으면 A의 맨 위에 있는 항목 혹은 B의 맨 위에 있는항목 혹은 C의 맨 위에 있는 항목을 선택하여 뽑아낼 수 있습니다. key를 사용하지 않으면 큐 맨 위에 있는 항목을 꺼냅니다.

2021-01-03 11:43 UTC, Dae-Hwa commented
@BKJang 말씀하신 부분 전체적으로 수정 완료 했습니다.

2021-01-04 14:30 UTC, SeonHyungJo requested changes
복습하는 느낌으로 보니까 좋군요 👍

2021-01-04 14:30 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +프로세스는 서로 접근이 불가능하다. 프로세스는 커널만 접근할 수 있기 때문이다. 하지만 병렬처리가 필요하거나 서로 다른 프로세스 간의 상호작용이 필요할 수 있다. 예시를 떠올리기 힘들다면 서버-클라이언트 모델을 생각해보면 이해하기 쉽다. 서버와 클라이언트는 서로 다른 프로세스이지만 정보를 주고받아야 한다. 이걸 해결하는 방법이 IPC(Inter Proce
IPC 말고 다른 방법들도 있는 건가요?

2021-01-04 14:30 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +파일을 이용한 IPC 외에는 크게 두 가지 컨셉이다. 프로세스끼리 공유할 수 있는 메모리를 만들어 함께 접근하거나, 메세지를 주고받는 것(메세지 패싱)이다.
```suggestion
파일을 이용한 IPC 외에는 크게 두 가지 컨셉이 있다. 프로세스끼리 공유할 수 있는 메모리를 만들어 함께 접근하거나, 메세지를 주고받는 것(메세지 패싱)이다. 
```

2021-01-04 14:30 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +-   양방향(bidirection)으로 구현하여도 반이중 통신이다.
전체적으로 간격이 넓네용??

2021-01-04 14:30 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +    >   busy wating : 특정 자원이 사용가능한지 계속 확인하는 것으로 자원 낭비가 일어날 수 있다.
```suggestion
-   임계 영역에 접근 가능한지 여부를 제공하기때문에 busy waiting을 사용하지 않아도 된다.    
    >   busy waiting : 특정 자원이 사용가능한지 계속 확인하는 것으로 자원 낭비가 일어날 수 있다.
```

2021-01-04 14:30 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +세마포어는 조금 특이하다. 원래는 동기화 이슈를 해결하기 위한 방법론 중 하나이기 때문이다. 동기화 이슈가 생기는(동시에 접근하면 안 되는) 부분을 임계 영역(critical section)이라고 한다. 여기에 대한 동시 접근을 막는 것을 상호배제(MUTial EXclusion; MUTEX)라고 하는데, 세마포어는 동시 접근 할 수 있는 프로세스의 개수를
오랜만에 들어보는 용어네요!!

2021-01-04 16:00 UTC, BKJang commented on CS/methods_in_IPC.md
> +시그널의 좀 더 자세한 동작 원리는 인터럽트가 종료되어 사용자 모드로 전환하는 시점에 pcb(process control block)에 있는 시그널과 관련된 자료구조의 상태를 확인하는 것이다. 이를 이용하여 다른 IPC 기법과 조합하여 사용할 수 있다. 데이터를 직접 전송할 수 없다는 단점이 있다.
@Dae-Hwa 저도 맘의 준비가 아직 안된 듯 하네요...😂
@jigi-kim 혹시 좀 더 쉽게 설명해주실 수 있나요?ㅠㅠ

2021-01-04 16:01 UTC, BKJang approved these changes
복습하는 느낌으로 발표를 들으니 이해가 쉬워서 좋았습니다. 주제 선정 👍
승인할게요 고생하셨습니다~

2021-01-04 16:19 UTC, jigi-kim commented on CS/methods_in_IPC.md
> +시그널의 좀 더 자세한 동작 원리는 인터럽트가 종료되어 사용자 모드로 전환하는 시점에 pcb(process control block)에 있는 시그널과 관련된 자료구조의 상태를 확인하는 것이다. 이를 이용하여 다른 IPC 기법과 조합하여 사용할 수 있다. 데이터를 직접 전송할 수 없다는 단점이 있다.
@BKJang 시그널은 H/W적으로 발생되는 개념이 아닌, 커널이 S/W적으로 프로세스에게 전달하는 알림의 개념입니다. (A 프로세스가 B 프로세스에 시그널을 발생시키더라도 결국 이를 전달해주는건 커널이 해야겠죠.)

커널이 A 프로세스에 시그널을 전달하기 위해서는, 스케줄링 단계에서 A 프로세스를 실행 상태로 전환할 때 A 프로세스에 전달해야 할 시그널이 있는지를 확인하고, 있다면 A 프로세스가 기존에 수행하던 코드로 점프하게 하는 대신 A 프로세스에 등록된 시그널 핸들러로 점프하도록 조작을 해야할 것이고요.

즉, 본문의 `인터럽트가 종료되어 사용자 모드로 전환하는 시점`이라는 것은 `기존의 프로세스가 wait or ready 상태로 전환되어  다음 프로세스를 골라 실행시키는 시점`를 의미하고, `시그널과 관련된 자료구조의 상태를 확인`한다는 것은 간단히 보면 `다음에 실행할 프로세스에게 알릴 시그널이 있는지를 확인`한다고 보면 될 것 같습니다.

물론 상태를 확인하는 단계에서 단순히 시그널 발생 여부만을 확인하는 것은 아닐테고, 해당 시그널을 무시하도록 되어 있는지와 같은 설정부터 프로세스가 시그널을 현재 받을 수 있는 상황인지 등 다양한 상태가 확인될 것 같습니다. 커널의 관련 코드를 자세히 본 적은 없어서 구체적으로 어떠한 부분들을 확인하는지까지는 저도 잘 모르겠네요. :)

2021-01-05 00:50 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +-   양방향(bidirection)으로 구현하여도 반이중 통신이다.
@SeonHyungJo 줄 간격 말씀하시는 것 같은데 혹시 사진 첨부해주실 수 있나요?

2021-01-05 00:53 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +프로세스는 서로 접근이 불가능하다. 프로세스는 커널만 접근할 수 있기 때문이다. 하지만 병렬처리가 필요하거나 서로 다른 프로세스 간의 상호작용이 필요할 수 있다. 예시를 떠올리기 힘들다면 서버-클라이언트 모델을 생각해보면 이해하기 쉽다. 서버와 클라이언트는 서로 다른 프로세스이지만 정보를 주고받아야 한다. 이걸 해결하는 방법이 IPC(Inter Proce
@SeonHyungJo 프로세스끼리 상호작용할 수 있는 방법이 모두 다 IPC인것으로 알고 있습니다.

2021-01-05 17:37 UTC, BKJang commented on CS/methods_in_IPC.md
> +시그널의 좀 더 자세한 동작 원리는 인터럽트가 종료되어 사용자 모드로 전환하는 시점에 pcb(process control block)에 있는 시그널과 관련된 자료구조의 상태를 확인하는 것이다. 이를 이용하여 다른 IPC 기법과 조합하여 사용할 수 있다. 데이터를 직접 전송할 수 없다는 단점이 있다.
@jigi-kim 크...이해됐습니다 감사합니다 👍

2021-01-08 15:42 UTC, SeonHyungJo commented on CS/methods_in_IPC.md
> +-   양방향(bidirection)으로 구현하여도 반이중 통신이다.
지금 위의 문서들이 스페이스가 2칸씩 되어있는건가요 탭으로 되어있는건가요?

2021-01-18 01:11 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +-   양방향(bidirection)으로 구현하여도 반이중 통신이다.
@SeonHyungJo 수정했습니다!

2021-01-18 02:00 UTC, SeonHyungJo approved these changes
좋은 주제였습니다. 수고하셨습니다.

2021-01-18 11:11 UTC, dididy requested changes
유익하게 잘 읽었습니다. 좋은 주제를 이해하기 쉽게 잘 정리해 주신 것 같네요. 

수고하셨습니다 👍👍

2021-01-18 11:11 UTC, dididy commented on CS/methods_in_IPC.md
> +- 프로세스 간의 비동기(asynchronition) 통신이 가능하다.
<img width="1066" alt="Screen Shot 2021-01-18 at 8 03 16 PM" src="https://user-images.githubusercontent.com/16266103/104907298-360bb400-59c8-11eb-929b-96885ea31264.png">
asynchroniton의 구글 검색 결과가 7개인 것을 보면 오타인듯 합니다. asynchronization을 의도하신 것 같네요

2021-01-18 11:11 UTC, dididy commented on CS/methods_in_IPC.md
> +- 프로그램의 규모가 작다면 오버헤드가 클 수 있다.
프로그램의 규모가 커지면 규모가 작을 때보다 비교적 오버헤드가 작다는 의미로 이해했는데 맞나요? 아니면 실제로 파이프같은 방식보다 오버헤드가 적어지는 것인가요?

2021-01-18 15:33 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +- 프로그램의 규모가 작다면 오버헤드가 클 수 있다.
@dididy 전자가 맞습니다.
다른 방식에 비해 소켓을 쓰면 발생하는 오버헤드가 큰 편이지만, 양방향으로 많은 데이터가 오고 가야 할 때 좀 더 다루기 쉬우므로 소켓을 쓰는 것이 좋다고 합니다.
다만, 그런 구현상의 이점을 가저갈 정도로 규모가 크지 않다면 비용이 저렴한 IPC 기법을 쓰는 것이 좋겠죠.
제가 이해한건 이정도인데, @jigi-kim 의 보충설명이 필요한 것 같기도 합니다. 🤔

2021-01-18 15:33 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +한 프로세스가 넣으면 다른 프로세스가 읽는 큐 형태의 구조이다. 하지만 방향이 고정되어있어 한 방향으로만 통신할 수 있다. 물탱크에서 관(파이프)을 통해 수도꼭지로 물이 나오는 것을 생각해보면 이해하기 쉽다. 즉, 파이프의 입력부분과 출력 부분이 정해지면 입력 부분이 구현된 프로세스에서는 입력만, 출력 부분이 구현된 프로세스에서는 출력만 가능하다. 또한,
감사합니다! 😁

2021-01-18 15:36 UTC, Dae-Hwa commented on CS/methods_in_IPC.md
> +- 프로세스 간의 비동기(asynchronition) 통신이 가능하다.
@dididy 수정했습니다. 감사합니다.

2021-01-18 15:45 UTC, EUNJIHA approved these changes
승인합니다

2021-01-19 17:48 UTC, jigi-kim commented on CS/methods_in_IPC.md
> +- 프로그램의 규모가 작다면 오버헤드가 클 수 있다.
설명하신 내용이 맞습니다. 큰 규모의 프로그램 상에서는 (전체 프로그램 수행 시간에 비해) 무시할 수 있을 정도의 오버헤드이지만, 규모가 작은 프로그램에 사용될 때에는 치명적이라는 이야기 같네요.

요즘에는 컴퓨팅 속도가 워낙 빠르고, 상용 가능한 수준의 S/W는 단위 기능 하나의 오버헤드로 인해 크게 성능이 좌우될만큼 규모가 작지 않기 때문에 사실상 응용 레벨에서는 오버헤드의 차이를 따지기 보다는 사용 목적/환경에 맞는 기능을 선택하는 경우가 많겠네요.

2021-01-20 15:30 UTC, dididy commented on CS/methods_in_IPC.md
> +- 프로그램의 규모가 작다면 오버헤드가 클 수 있다.
@Dae-Hwa @jigi-kim 답변 감사합니다~

2021-01-20 15:31 UTC, dididy approved these changes
수고 많으셨어요~!

2021-01-20 15:31 UTC, merged