3-way handshaking & 4-way handshaking.md
im-d-team/Dev-Docs pull request #204
Opened 2021-01-03 05:08 UTC by JegalEun

✏️ :JegalEun/3-way handshaking & 4-way handshaking.md

2021-01-04 04:54 UTC, BKJang commented on Network/3-way handshaking & 4-way handshaking.md
> +이번 시간에는 TCP 통신에서 쓰이는 `3-way handShaking`과 `4-way handShaking`을 정리해보았다.
이 이전에 제목이 들어가면 좋을 것 같습니다.

2021-01-04 04:56 UTC, BKJang commented on Network/3-way handshaking & 4-way handshaking.md
> +- 연속성보다 신뢰성 있는 전송이 중요할 때에 사용된다.
발표 때 얘기가 나왔던 것 처럼 이 부분에 대한 추가적인 설명이 조금이라도 더 있으면 좋을 것 같습니다.
연속성과 신뢰성을 좀 구체적으로 설명할 수 있으면 좋을 것 같아요 😄

2021-01-04 04:58 UTC, BKJang commented on Network/3-way handshaking & 4-way handshaking.md
> +여기서 시퀀스 번호를 보내는데, 처음에 시퀀스 번호를 ISN(Initial Sequence Number)이라고 한다. ISN은 난수의 숫자를 생성해 보낸다고 한다. 왜 순차적인 번호가 아닌 난수일까?
여기서 하나 궁금한게 있는데, ISN 즉 최초의 시퀀스 번호만 난수로 생성하는 것인가요?

2021-01-04 05:00 UTC, BKJang commented on Network/3-way handshaking & 4-way handshaking.md
> +3. 서버는 데이터를 모두 보내고 연결 해지할 준비 완료되었다는 메시지 전송한다. (FIN)
```suggestion
3. 서버는 데이터를 모두 보내고 연결 해지할 준비 완료되었다는 메시지를 전송한다. (FIN)
```

2021-01-04 05:01 UTC, BKJang requested changes
다시 한 번 하나씩 네트워크의 기본 적인 내용을 훑을 수 있어서 좋은 것 같습니다.
커멘트 피드백 부탁드려요 😄

2021-01-04 14:20 UTC, SeonHyungJo requested changes
몇가지 질문사항 남겼습니다. 점점 주제가 좋아지네요.

2021-01-04 14:20 UTC, SeonHyungJo commented on Network/3-way handshaking & 4-way handshaking.md
> +TCP는 OSI 7계층 중 **전송 계층**에서 사용하는 프로콜로서, 장치들 사이에 논리적인 접속을 위한 연결을 설정하여 **신뢰성을 보장**하는 연결형 서비스이다.
```suggestion
TCP는 OSI 7계층 중 **전송 계층**에서 사용하는 프로토콜로서, 장치들 사이에 논리적인 접속을 위한 연결을 설정하여 **신뢰성을 보장**하는 연결형 서비스이다.
```

프로토콜을 의미하는 걸까요?

2021-01-04 14:20 UTC, SeonHyungJo commented on Network/3-way handshaking & 4-way handshaking.md
> +- 연결형 서비스로 흐름제어 및 혼잡제어를 제공한다.
작성해주신 글의 링크를 추가하는 것도 좋아보입니다.

2021-01-04 14:20 UTC, SeonHyungJo commented on Network/3-way handshaking & 4-way handshaking.md
> +헤더는 3-way handshaking을 설명하기 위한 일부만 하고 나머지 요소는 @sNyung님의 [TCP와 UDP](https://github.com/im-d-team/Dev-Docs/blob/master/Network/TCP%20%26%20UDP.md) 글을 참고 바람!
ㅋㅋㅋㅋㅋㅋ참조 고맙습니다. 😄

2021-01-04 14:20 UTC, SeonHyungJo commented on Network/3-way handshaking & 4-way handshaking.md
> +TCP 통신을 이용하여 데이터를 전송하기 위해서는 네트워크 연결을 설정하는 과정이 필수적이다. 네트워크 연결을 하기 위해서 TCP는 `3-way handShaking`이라는 과정을 거친다.
handShaking인가요 handshaking인가요 통일해서 작성해주시는게 좋을 듯합니다.

2021-01-13 12:46 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +이번 시간에는 TCP 통신에서 쓰이는 `3-way handShaking`과 `4-way handShaking`을 정리해보았다.
앗 깜빡했네요! 수정했습니다.

2021-01-13 12:48 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +여기서 시퀀스 번호를 보내는데, 처음에 시퀀스 번호를 ISN(Initial Sequence Number)이라고 한다. ISN은 난수의 숫자를 생성해 보낸다고 한다. 왜 순차적인 번호가 아닌 난수일까?
네 최초의 시퀀스 번호만 난수로 설정하고 그 후의 시퀀스 번호는 난수+윈도우사이즈 로 설정됩니다.

만약 윈도우사이즈가 4고  ISN이 100이면 seq#2는 104가 되고 seq#3는 108이 됩니다.

2021-01-13 12:49 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +3. 서버는 데이터를 모두 보내고 연결 해지할 준비 완료되었다는 메시지 전송한다. (FIN)
수정하였습니다 ㅎㅎ

2021-01-13 12:50 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +TCP는 OSI 7계층 중 **전송 계층**에서 사용하는 프로콜로서, 장치들 사이에 논리적인 접속을 위한 연결을 설정하여 **신뢰성을 보장**하는 연결형 서비스이다.
오 맞아요 ㅠㅠ 오타 났네요

2021-01-13 12:50 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +TCP 통신을 이용하여 데이터를 전송하기 위해서는 네트워크 연결을 설정하는 과정이 필수적이다. 네트워크 연결을 하기 위해서 TCP는 `3-way handShaking`이라는 과정을 거친다.
넵 handshaking으로 통일하였습니다 !

2021-01-13 13:32 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +- 연속성보다 신뢰성 있는 전송이 중요할 때에 사용된다.
연속성이라는 것은 중간에 데이터가 유실되더라도 끊기지 않고 전송하는 것을 뜻합니다. 
신뢰성은 데이터의 도착 유무를 확인해 정확한 전송을 보장한다는 점에서 신뢰성이 높다고 표현합니다. 

더욱 자세한 설명은 글에 추가하겠습니다 ㅎㅎ

2021-01-13 13:43 UTC, JegalEun commented on Network/3-way handshaking & 4-way handshaking.md
> +- 연결형 서비스로 흐름제어 및 혼잡제어를 제공한다.
추가하였습니다 :)

2021-01-13 14:11 UTC, BKJang approved these changes
답변 내용을 보니 글을 작성할 때 이해도가 이전보다 훨씬 올라간 것 같아요 👍 
고생하셨어요~
승인하겠습니다. 피드백 감사합니다 😄

2021-01-14 13:59 UTC, SeonHyungJo approved these changes
고생하셨습니다

2021-01-18 11:35 UTC, dididy requested changes
해당 개념에 대해 왜 필요한지, 어떻게 동작하는지 알기쉽게 설명되어있어서 잘 이해될 수 있었습니다.

수고하셨어요~ 👍👍

2021-01-18 11:35 UTC, dididy commented on Network/3-way handshaking & 4-way handshaking.md
> +통신도 마찬가지로 데이터를 보내기 전에 내가 보낼 데이터를 상대방이 받을 수 있는지 먼저 확인해야 한다.
왜 3번 해야하는지 명확하게 이해가 되네요 👍

2021-01-18 11:35 UTC, dididy commented on Network/3-way handshaking & 4-way handshaking.md
> +|SYN-RECEVED|SYN+ACK을 보내고 ACK를 기다리는 상태|
```suggestion
|SYN-RECEIVED|SYN+ACK을 보내고 ACK를 기다리는 상태|
```
아마 SYN-RECEIVED를 의도하신 것 같아요

2021-01-22 17:51 UTC, EUNJIHA reviewed
이 글 덕분에 4-way handshaking을 알게 되었습니다. 리뷰 확인 부탁드립니다!

2021-01-22 17:51 UTC, EUNJIHA commented on Network/3-way handshaking & 4-way handshaking.md
> +5. 서버는 클라이언트의 확인 메시지를 받고 소켓 연결을 닫는다 (CLOSE)
4-way handshaking은 3. 서버는 데이터를 모두 보내고 FIN을 보낸다. 이 부분 때문에 3-way handshaking 과 달리 1 way 가 한 번 더 추가된거 같은데, ACK와 FIN을 동시에 보내지 않고 ACK를 보내고 데이터를 모두 보냈음을 확인한 뒤에 FIN을 보내는 이유가 무엇인지 궁금합니다!

2021-01-27 02:28 UTC, Dae-Hwa requested changes
작성해놓고 submit을 안했었네요. 늦게 리뷰해 죄송합니다.

2021-01-27 03:02 UTC, BKJang commented on Network/3-way handshaking & 4-way handshaking.md
> +5. 서버는 클라이언트의 확인 메시지를 받고 소켓 연결을 닫는다 (CLOSE)
제가 알고 있는 지식이 맞는지는 모르겠지만, 대신 답변드리면 연결을 종료할 때는 연결을 시작할 때와 달리 서버에서 작업중이던 task를 완료해야합니다. 작업을 완료한 이후 FIN을 보낸다고 보면 될 것 같습니다

2021-04-18 06:01 UTC, BKJang approved these changes
해당 글은 일단 머지후 추후 다시 진행하는 방향으로 하겠습니다.

2021-04-18 06:01 UTC, merged