Storybook
im-d-team/Dev-Docs pull request #205
Opened 2021-01-03 05:51 UTC by dididy

2021-01-05 12:00 UTC, BKJang commented on Javascript/Storybook.md
> +프론트엔드에서컴포넌트 단위로 개발을 진행하는 경우 해당 컴포넌트의 UI를 독립적으로 개발 및 테스트하며 작업하고자 한다면 어떻게 해야 할까? Storybook을 사용하면 원하는 방식으로 작업 할 수 있다.
```suggestion
프론트엔드에서 컴포넌트 단위로 개발을 진행하는 경우 해당 컴포넌트의 UI를 독립적으로 개발 및 테스트하며 작업하고자 한다면 어떻게 해야 할까? Storybook을 사용하면 원하는 방식으로 작업 할 수 있다.
```

2021-01-05 12:01 UTC, BKJang commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. Storybook을 개발 툴로 볼 수도 있지만, 테스팅 툴로 주로 쓰지 않나요?

2021-01-05 12:02 UTC, BKJang commented on Javascript/Storybook.md
> +CRA(Creat React App) 으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보겠다.
```suggestion
CRA(Creat React App)으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보겠다.
```

2021-01-05 12:04 UTC, BKJang requested changes
용재님은 항상 경험에 기반한 글을 작성해주시는게 좋은 것 같습니다.
해당 글을 좀 더 발전시켜서 저희 블로그 글에도 넣으면 좋을 것 같아요.
재밌게 발표 잘 들었습니다. 피드백 부탁드려요 👍

2021-01-05 14:44 UTC, dididy commented on Javascript/Storybook.md
> +프론트엔드에서컴포넌트 단위로 개발을 진행하는 경우 해당 컴포넌트의 UI를 독립적으로 개발 및 테스트하며 작업하고자 한다면 어떻게 해야 할까? Storybook을 사용하면 원하는 방식으로 작업 할 수 있다.
@BKJang 반영하였습니다~

2021-01-05 14:45 UTC, dididy commented on Javascript/Storybook.md
> +CRA(Creat React App) 으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보겠다.
@BKJang 반영하였습니다. 본문에 비슷한 띄어쓰기 오류가 있어 그것 또한 수정하였습니다!

2021-01-05 14:49 UTC, dididy commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
@BKJang 
<img width="756" alt="Screen Shot 2021-01-05 at 11 43 55 PM" src="https://user-images.githubusercontent.com/16266103/103659813-2fd10d00-4fb0-11eb-9ab7-5c04a2f6b9dc.png">

일단 [공식문서](https://storybook.js.org/docs/react/get-started/introduction)에는 `tool for UI development` 라고 명시되어 있는 것 같아요 테스팅에 대한 언급도 추가하겠습니다!

2021-01-05 14:53 UTC, dididy commented on Javascript/Storybook.md
> +프론트엔드에서컴포넌트 단위로 개발을 진행하는 경우 해당 컴포넌트의 UI를 독립적으로 개발 및 테스트하며 작업하고자 한다면 어떻게 해야 할까? Storybook을 사용하면 원하는 방식으로 작업 할 수 있다.
```
Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다. Storybook을 사용하면 UI 테스트를 손쉽게 할 수 있으므로 테스팅 툴로서 많이 사용되고 있다.
```
요렇게 수정하려고 하는데 괜찮을까요?

2021-01-05 14:54 UTC, dididy commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
```
Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다. Storybook을 사용하면 UI 테스트를 손쉽게 할 수 있으므로 테스팅 툴로서 많이 사용되고 있다.
```
요렇게 수정하려고 하는데 괜찮을까요?

2021-01-05 14:57 UTC, dididy commented
> 용재님은 항상 경험에 기반한 글을 작성해주시는게 좋은 것 같습니다.
> 해당 글을 좀 더 발전시켜서 저희 블로그 글에도 넣으면 좋을 것 같아요.
> 재밌게 발표 잘 들었습니다. 피드백 부탁드려요 👍

네 저도 현재 진행하는 프로젝트에 여러 add-on을 써보면서 사용 범위를 확장해보려 합니다. 거기서 얻은 인사이트를 바탕으로 좀 더 전문적인 글을 작성할 수 있을 것 같아요!

2021-01-06 10:53 UTC, SeonHyungJo requested changes
잘 읽었습니다. 항상 좋은 주제가 많아지고 있어서 좋네요.

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
```suggestion
Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
```

UI 테스트 도구라는 느낌만 들어가면 될 듯합니다.

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +CRA(Creat React App) 으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보겠다.
```suggestion
CRA(Creat React App) 으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보자.
```

위에서도 ~보자 라고 적으셔서 동일하게 했습니다

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +이번에는 `App.js`에 Props를 전달할 수 있도록 수정하고 Props에 따른 Storybook 항목을 생성해보도록 하겠다.
동일하게 ~보자 라눈게 통일감이 있어보입니다

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +이번 글을 통해 Storybook이 무슨 목적을 위해 사용되는지, 어떻게 설정하는지에 대하여 설명해보았다. 나의 경우 Storybook이 생산성에 긍정적인 영향을 주어 최근 거의 모든 프로젝트마다 필수적으로 설정하여 사용하고 있다. 특히 협업할 때 매우 유용하다.
유용하다고 적어주셨는데 이부분을 자세히 적어주면 더 공감할만한 글이 될 수 있을거 같습니다.

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +아쉽게도 아직 설명하지 못한 Storybook의 강력한 기능들이 많다. Storybook의 심화적인 부분에 대해서는 다음에 기회가 되면 다뤄볼 예정이다.
할게 하나 더 늘어나셨군요

2021-01-06 10:53 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +이번 글을 통해 Storybook이 무슨 목적을 위해 사용되는지, 어떻게 설정하는지에 대하여 설명해보았다. 나의 경우 Storybook이 생산성에 긍정적인 영향을 주어 최근 거의 모든 프로젝트마다 필수적으로 설정하여 사용하고 있다. 특히 협업할 때 매우 유용하다.
말씀드린 것처럼 프론트엔드도 중요하지만 디자이너와 협업을 할 기회가 있다면 좋을거 같습니다

그리고 추가적으로 공통의 컴포넌트만 한 명의 개발자가 담당해서 개발하는 방법도 해보시면 좋을거 같습니다

2021-01-06 11:57 UTC, BKJang commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
@SeonHyungJo storybook이 테스팅 툴로서 사용되는게 맞죠? 제 개인적인 견해일까 싶어서요

2021-01-06 11:58 UTC, BKJang approved these changes
일단 승인하도록 할게요~ 고생하셨습니다 👍

2021-01-06 15:01 UTC, dididy commented on Javascript/Storybook.md
> +아쉽게도 아직 설명하지 못한 Storybook의 강력한 기능들이 많다. Storybook의 심화적인 부분에 대해서는 다음에 기회가 되면 다뤄볼 예정이다.
😂

2021-01-06 15:02 UTC, dididy commented on Javascript/Storybook.md
> +이번 글을 통해 Storybook이 무슨 목적을 위해 사용되는지, 어떻게 설정하는지에 대하여 설명해보았다. 나의 경우 Storybook이 생산성에 긍정적인 영향을 주어 최근 거의 모든 프로젝트마다 필수적으로 설정하여 사용하고 있다. 특히 협업할 때 매우 유용하다.
네 기회가 된다면 시도해보도록 하겠습니다~

2021-01-06 15:08 UTC, dididy commented on Javascript/Storybook.md
> +이번에는 `App.js`에 Props를 전달할 수 있도록 수정하고 Props에 따른 Storybook 항목을 생성해보도록 하겠다.
반영하였습니다!

2021-01-06 15:08 UTC, dididy commented on Javascript/Storybook.md
> +CRA(Creat React App) 으로 React 프로젝트를 생성할 경우 자동으로 만들어지는 App.js를 Storybook에서 확인해볼 수 있도록 해보겠다.
반영하였습니다!

2021-01-06 15:12 UTC, dididy commented on Javascript/Storybook.md
> +이번 글을 통해 Storybook이 무슨 목적을 위해 사용되는지, 어떻게 설정하는지에 대하여 설명해보았다. 나의 경우 Storybook이 생산성에 긍정적인 영향을 주어 최근 거의 모든 프로젝트마다 필수적으로 설정하여 사용하고 있다. 특히 협업할 때 매우 유용하다.
@SeonHyungJo 추가하였습니다!

2021-01-08 15:44 UTC, SeonHyungJo commented on Javascript/Storybook.md
> +Storybook은 프론트엔드 UI 컴포넌트 개발 도구이다. React, Vue, Angular 등 컴포넌트 단위로 개발을 하는 프레임워크(혹은 라이브러리)에 적용하여 사용해볼 수 있다.
@BKJang 테스팅 툴로도 사용할 수 있다가 더 맞을 거 같습니다. 스토리북은 Atomic 개발을 하게 되면서 화면 개발에 있어 각각의 컴포넌트가 어떤게 개발되어있고 어떻게 사용할 수 있는지 알려주고 어떻게 사용하는 지 보여주는 용도가 강하긴합니다.

2021-01-08 15:45 UTC, SeonHyungJo approved these changes
승인하겠습니다.

2021-01-08 17:43 UTC, jigi-kim requested changes
문서 내용에 대한 수정/확인 요청을 남깁니다.

2021-01-08 17:43 UTC, jigi-kim commented on Javascript/Storybook.md
> +cd <Project Directory>
```suggestion
$ cd <Project Directory>
```

2021-01-08 17:43 UTC, jigi-kim commented on Javascript/Storybook.md
> +Storybook에 각 컴포넌트를 연결하기 위해서는 `<filename>.stories.js` 와 같이 파일명과 확장자명 사이에 `stories` 문자열을 comma(`.`) 사이에 넣어주면 된다. Storybook 실행 환경 설정 시 만들어지는 `./src/stories` 폴더를 보면 `Button.stories.js`, `Header.stories.j
```suggestion
Storybook에 각 컴포넌트를 연결하기 위해서는 `<filename>.stories.js` 와 같이 파일명과 확장자명 사이에 `stories` 문자열을 dot(`.`) 사이에 넣어주면 된다. Storybook 실행 환경 설정 시 만들어지는 `./src/stories` 폴더를 보면 `Button.stories.js`, `Header.stories.js`, `Page.stories.js` 이렇게 세 개의 예시를 확인해볼 수 있다.
```

2021-01-11 14:19 UTC, dididy commented on Javascript/Storybook.md
> +cd <Project Directory>
@jigi-kim 반영하였습니다~

2021-01-11 14:19 UTC, dididy commented on Javascript/Storybook.md
> +Storybook에 각 컴포넌트를 연결하기 위해서는 `<filename>.stories.js` 와 같이 파일명과 확장자명 사이에 `stories` 문자열을 comma(`.`) 사이에 넣어주면 된다. Storybook 실행 환경 설정 시 만들어지는 `./src/stories` 폴더를 보면 `Button.stories.js`, `Header.stories.j
@jigi-kim 반영하였습니다~

2021-01-12 12:22 UTC, jigi-kim approved these changes

2021-01-22 18:00 UTC, EUNJIHA approved these changes
Storybook을 처음 접했을 때 Getting started로 매우 좋은 글인거 같습니다. 승인합니다!

2021-01-22 18:00 UTC, merged