SWR
im-d-team/Dev-Docs pull request #206
Opened 2021-01-09 14:07 UTC by SeonHyungJo

2021-01-11 08:00 UTC, BKJang commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
Preact로 프로젝트 구성을 하게된 이유가 있을까요? 제대로 사용해본적이 없어서 이론 상 장점만 알고 실제로는 어떤지 궁금하네요

2021-01-11 08:01 UTC, BKJang commented on React/SWR.md
> +한 가지 아쉬운 것은 Fetching 이외의 수정, 삭제는 따로 개발해서 사용해야한다.
확실히 아쉬운 부분이긴 하네요ㅠ

2021-01-11 08:02 UTC, BKJang approved these changes
사실, 발표 때 해소된 부분이 많아 컨텐츠에 대한 질문보다는 실제로 사용했을 때 어떤 장점이 있는지 궁금하긴 하네요.
시간될 때 저도 한 번 해봐야겠습니다.
질문 하나만 답변 부탁드릴게요ㅎㅎ 미리 승인은 하도록 하겠습니다 :)

2021-01-11 08:49 UTC, SeonHyungJo commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
먼저 React 보다는 가벼운게 우선이었습니다. 가볍게 가져갈 프로젝트이면서 추후에 변경이 쉬워야한다고 생각해서 선택했고, SSR, pre-rendering 같은 기능이 기본으로 제공되는게 많아서 선택했습니다.

2021-01-13 07:45 UTC, dididy requested changes
정의된 문제를 swr을 사용해 어떻게 해결할 수 있는지 명확하게 잘 설명해주신 것 같습니다. 

재미있게 잘 읽었습니다!

2021-01-13 07:45 UTC, dididy commented on React/SWR.md
> +props의 사용을 피하기 위해서 Context를 사용한다. 이 역시 Dynamic Component에서 문제가 발생한다. 페이지 내 Component가 Dynamic 할 경우 최상위 컴포넌트는 자식 컴포넌트의 어떤 데이터가 필요한지 알지못할 수 있다.
Dynamic Component란 무엇인가요?

2021-01-13 07:45 UTC, dididy commented on React/SWR.md
> +같은 SWR 키를 사용하면, 요청에 대해 자동으로 중복제거, 캐시, 공유되어 API 요청이 하나만으로 가능하다.
혹시 fetch를 한 response가 기존 캐싱된 값과 같은 값인 경우 리렌더가 발생하지 않는거죠?

2021-01-13 07:45 UTC, dididy commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
mutate가 왜 필요한지 명확하게 이해한 것 같습니다. 혹시 이부분도 미리 로컬 데이터를 업데이트하고 서버의 response 데이터와 유효성을 검사했는데 같은 값일 경우 리렌더가 발생하지 않도록 swr 자체적으로 최적화 되어있는게 맞죠?

2021-01-13 07:45 UTC, dididy commented on React/SWR.md
> +한 가지 아쉬운 것은 Fetching 이외의 수정, 삭제는 따로 개발해서 사용해야한다.
swr만 사용하기는 힘들겠군요.. 그래도 장점이 많아 충분히 매력적인 것 같습니다!

2021-01-13 08:10 UTC, SeonHyungJo commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
@dididy 번들링이라는 과정은 거칩니다. 결국 sass를 사용하고 다른 라이브러리를 사용하면 html, js, css로 만들어주는 과정과 함께 합쳐주어야 하니까요. 대신 개발단계에서 필요없는 것이죠. 대신 vite는 빌드를 하고 나면 index.html에는

```html
<script type="module" crossorigin src="/assets/index.2c3f4082.js"></script>
```

와 같이 module 타입으로 들어가게 됩니다. 이유는 vite는 애초에 ie를 지원하지 않을 목적으로 나왔기 때문입니다.

그래도 ie를 지원하고 싶으면 최신버전 기준 `@vitejs/plugin-legacy`를 사용하시면 ie도 가능합니다.

2021-01-13 08:12 UTC, SeonHyungJo commented on React/SWR.md
> +같은 SWR 키를 사용하면, 요청에 대해 자동으로 중복제거, 캐시, 공유되어 API 요청이 하나만으로 가능하다.
리렌더링에 관한 부분은 SWR보다는 React나 Preact의 영역 같습니다. 결국 값이 다르면 렌더링해주는건 React니까요?

2021-01-13 08:13 UTC, SeonHyungJo commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
값이 같으면 SWR 내부의 Cache 스토어의 값을 변경하지 않는 것으로 알고 있습니다. 리렌더링 관련해서는 위에서 언급한 것과 같이 React 또는 Preact 소관인 것으로 보입니다.

2021-01-13 08:14 UTC, SeonHyungJo commented on React/SWR.md
> +한 가지 아쉬운 것은 Fetching 이외의 수정, 삭제는 따로 개발해서 사용해야한다.
발표당시에 잠깐 나왔는데 react-query라는 것도 있습니다.

stale-while-revalidation에 대해서 찾아보고 공부하면 도움이 될 거 같습니다.

2021-01-13 08:18 UTC, SeonHyungJo commented on React/SWR.md
> +props의 사용을 피하기 위해서 Context를 사용한다. 이 역시 Dynamic Component에서 문제가 발생한다. 페이지 내 Component가 Dynamic 할 경우 최상위 컴포넌트는 자식 컴포넌트의 어떤 데이터가 필요한지 알지못할 수 있다.
이 부분에 대해서 공식사이트에서 찾아보려고 했는데 못찾아서 다른 사이트를 공유해 드릴게요.

https://medium.com/@Carmichaelize/dynamic-tag-names-in-react-and-jsx-17e366a684e9

쉽게 말해서 컴포넌트를 변수로 넘겨서 변수에 담김 컴포넌트를 렌더링하는 것으로 생각하시면 됩니다. 이렇게 되면 변수에 담긴 컴포넌트가 무엇이냐에 따라 props가 달라져야하는데 변수에 담긴 컴포넌트가 어떤 것인지 명시적으로 알 수 없어 props를 정할 수 없다는게 문제입니다.

2021-01-13 08:46 UTC, dididy approved these changes
수고 많으셨습니다. 이것저것 많이 배울 수 있어서 좋았습니다.

2021-01-13 08:46 UTC, dididy commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
아하 그럼 모던브라우저의 경우 트랜스파일 필요 없이 자바스크립트의 module(es6)을 지원 하는데 하위호환(ie 등) 고려 안하고 만들어진 빌드 툴 중 하나가 Vite라고 보면 되는 것이죠? 이러한 특성 덕분에 개발시에는 번들링 없이 사용할 수 있고 빌드시에는 번들링된 결과물이 나오게 되는 것이겠네요

2021-01-13 08:46 UTC, dididy commented on React/SWR.md
> +props의 사용을 피하기 위해서 Context를 사용한다. 이 역시 Dynamic Component에서 문제가 발생한다. 페이지 내 Component가 Dynamic 할 경우 최상위 컴포넌트는 자식 컴포넌트의 어떤 데이터가 필요한지 알지못할 수 있다.
아하 어떤 개념인지 이해했습니다. 글 읽어보도록 하겠습니다!

2021-01-13 08:46 UTC, dididy commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
아하 맞습니다 리렌더링은 React와 Preact 등에서 담당하는 부분이긴 하지요 캐시 스토어 값이 변경되지 않는군요 답변 감사합니다!

2021-01-13 08:47 UTC, dididy commented on React/SWR.md
> +한 가지 아쉬운 것은 Fetching 이외의 수정, 삭제는 따로 개발해서 사용해야한다.
학습해보도록 하겠습니다~

2021-01-13 08:58 UTC, dididy commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
아하 그럼 모던브라우저의 경우 트랜스파일 필요 없이 자바스크립트의 module(es6)을 지원 하는데 하위호환(ie 등) 고려 안하고 만들어진 빌드 툴 중 하나가 Vite라고 보면 되는 것이죠? 이러한 특성 덕분에 개발시에는 번들링 없이 사용할 수 있고 빌드시에는 번들링된 결과물이 나오게 되는 것이겠네요

2021-01-13 08:58 UTC, dididy commented on React/SWR.md
> +props의 사용을 피하기 위해서 Context를 사용한다. 이 역시 Dynamic Component에서 문제가 발생한다. 페이지 내 Component가 Dynamic 할 경우 최상위 컴포넌트는 자식 컴포넌트의 어떤 데이터가 필요한지 알지못할 수 있다.
어떤 개념인지 이해했습니다. 글 읽어보도록 하겠습니다!

2021-01-13 08:59 UTC, dididy commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
맞습니다 리렌더링은 React와 Preact 등에서 담당하는 부분이긴 하지요 캐시 스토어 값이 변경되지 않는군요 답변 감사합니다!

2021-01-15 00:23 UTC, BKJang commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
@dididy swr 자체적으로 리렌더링을 막는다기 보다는 swr을 사용했을 때 상태의 변화가 일어나면 React든 Preact든 리렌더링을 하게 된다고 이해하는게 맞지 않을까 생각이 들긴 합니다.
@SeonHyungJo 제가 이해한게 맞을까요?

2021-01-27 02:30 UTC, Dae-Hwa approved these changes
승인합니다

2021-01-27 04:54 UTC, EUNJIHA reviewed
흥미로운 주제입니다. 리뷰 확인 부탁드립니다!

2021-01-27 04:54 UTC, EUNJIHA commented on React/SWR.md
> +그러나 상위 컴포넌트에 모든 것을 하게 되면서 관리의 어려움이 발생한다.
혹시 어떤 예시가 있을까요? A, B 컴포넌트에서 상위 컴포넌트에 있는 데이터를 사용할 경우, A 컴포넌트에서 무엇인가를 변경한다면 B는 의도치 않은 결과를 얻을 수도 있다 의 맥락으로 이해해도 될까요?

2021-01-27 04:54 UTC, EUNJIHA commented on React/SWR.md
> +SWR의 전략은 캐싱된 데이터가 있으면 먼저 가져오며, 서버 데이터 가져온 후 마지막으로 최신의 데이터를 업데이트한다.
결국 마지막에는 서버로부터 최신의 데이터를 업데이트 하게 되는데, 이전에 캐싱된 데이터를 먼저 가져온다는 것은 클라이언트 쪽에서 로딩 시간을 줄이기 위함으로 이해하면 될까요?

2021-01-27 04:54 UTC, EUNJIHA commented on React/SWR.md
> +props의 사용을 피하기 위해서 Context를 사용한다. 이 역시 Dynamic Component에서 문제가 발생한다. 페이지 내 Component가 Dynamic 할 경우 최상위 컴포넌트는 자식 컴포넌트의 어떤 데이터가 필요한지 알지못할 수 있다.
저도 궁금했는데 @dididy @SeonHyungJo 님 덕분에 이해했습니다!

2021-01-29 01:58 UTC, SeonHyungJo commented on React/SWR.md
> +새로운 프로젝트를 하게 되면서, 프로젝트에 적용할 많은 새로운 스펙을  찾아보았고, **Preact + Vite**를 메인으로 사용하였다. 관련하여 글을 작성하였으니 궁금하면 [Preact, Vite 일주일 사용후기](https://snyung.com/content/2020-12-20--Preact%20Vite%20%EC%9D%BC%EC%A3%BC%EC%
그런데 결과적으로 ei11을 지원하지 않는 선으로 빌드해줍니다.(기본값이)

2021-01-29 02:01 UTC, SeonHyungJo commented on React/SWR.md
> +`mutate`를 사용하면 로컬 데이터를 업데이트하는 동시에 유효성을 다시 검사하고 최신 데이터로 바꿀 수 있다.
swr 내부적으로 비교하는 작업을 하긴합니다. https://www.npmjs.com/package/dequal 이 라이브러리를 사용해서 캐싱해둔 데이터와 같은지 비교는 하고 있습니다. 그렇다고 @BKJang 님이 말씀해주신 것처럼 리렌더링을 막는건 아니죠.

2021-01-29 02:03 UTC, SeonHyungJo commented on React/SWR.md
> +그러나 상위 컴포넌트에 모든 것을 하게 되면서 관리의 어려움이 발생한다.
이 문맥의 주요하게 봐야하는 것은 상위 컴포넌트에서 하위 컴포넌트에서 이루어지는 상태를 관리하지 말자라는 것이었어요. 

@EUNJIHA 말씀해주신 부분도 그 중 하나가 될 수 있습니다.

2021-01-29 02:04 UTC, SeonHyungJo commented on React/SWR.md
> +SWR의 전략은 캐싱된 데이터가 있으면 먼저 가져오며, 서버 데이터 가져온 후 마지막으로 최신의 데이터를 업데이트한다.
로딩을 줄이기 보다는 경험을 좋게하기 위해서에요. 만약 변경되지 않은 데이터인데 로딩때문에 화면에 보여지는 시간이 길어지는 것을 막기 위해서입니다. 

물론 캐싱된 데이터를 보여주다가 최신 데이터로 변경되는게 나중에 보이게 되면 문제가 되지만 그것도 따로 처리하는 방법이 있습니다.

2021-02-01 12:50 UTC, EUNJIHA approved these changes
승인합니다

2021-02-01 12:51 UTC, merged