JPA
im-d-team/Dev-Docs pull request #207
Opened 2021-01-10 06:08 UTC by EUNJIHA

2021-01-13 14:09 UTC, BKJang approved these changes
발표 후 질문 시간에 궁금증에 대한 해소가 대부분 된 것 같아 바로 승인하겠습니다.
@Dae-Hwa 님의 강의도 한 몫 했네요ㅋㅋ
고생하셨어요 👍

2021-01-27 02:24 UTC, Dae-Hwa approved these changes

2021-01-27 02:24 UTC, Dae-Hwa commented on Java/JPA.md
> +### 1. 상속
아래에 나오는 항목들에 DTO 예시도 필요할 것 같습니다.

2021-01-27 02:25 UTC, Dae-Hwa requested changes

2021-01-27 02:25 UTC, Dae-Hwa commented on Java/JPA.md
> +### 1. 상속
아래에 나오는 항목들에 DTO 예시도 필요할 것 같습니다.

2021-02-01 14:49 UTC, jigi-kim requested changes
문서 내용에 대한 질문 및 수정/확인 요청을 남깁니다.

2021-02-01 14:49 UTC, jigi-kim commented on Java/JPA.md
> +테이블은 외래 키를 사용한다. JOIN ON M.TEAM_ID = T.TEAM_ID
```suggestion
객체는 참조를 사용하고 `member.getTeam();`

테이블은 외래 키를 사용한다. `JOIN ON M.TEAM_ID = T.TEAM_ID`
```

2021-02-01 14:49 UTC, jigi-kim commented on Java/JPA.md
> +}
해당 예시가 조회에 대한 예시가 맞나요? `memberId` 실종...

2021-02-01 14:49 UTC, jigi-kim commented on Java/JPA.md
> +[Layerd Architecture](https://walbatrossw.github.io/etc/2018/02/26/etc-layered-architecture.html) 즉, 물리적으로는 계층을 잘 나눴다고 해도 실제 SQL이 어떻게 실행되었느냐에 따라서 Entity의 신뢰 문제가 생긴다.
```suggestion
Layered Architecture
![layered architecture](https://user-images.githubusercontent.com/43839938/104115545-cf492380-5353-11eb-88de-a84b69391d3c.png)



[Layered Architecture](https://walbatrossw.github.io/etc/2018/02/26/etc-layered-architecture.html) 즉, 물리적으로는 계층을 잘 나눴다고 해도 실제 SQL이 어떻게 실행되었느냐에 따라서 Entity의 신뢰 문제가 생긴다.
```

2021-02-15 03:21 UTC, SeonHyungJo approved these changes
바로 승인하겠습니다. 수고하셨습니다. 👍

2021-05-16 07:01 UTC, BKJang commented
추후 작성하기로 하고 close 처리

2021-05-16 07:01 UTC, closed without merging