React Server Component
im-d-team/Dev-Docs pull request #210
Opened 2021-01-23 16:57 UTC by SeonHyungJo

2021-01-28 05:42 UTC, Dae-Hwa requested changes

2021-01-28 05:42 UTC, Dae-Hwa commented on React/React Server Components.md
> +우리는 Client Side의 SSR은 차선책으로 사용한다. Server에서 HTML String을 만들어서 내려준다. 만들어진 HTML은 브라우저로 가서 First Contentful Paint 또는 Largest Contentful Paint로 보인다.
SSR이 차선책이라는 부분이 이상합니다!

2021-02-08 11:20 UTC, BKJang approved these changes
어쩌면 자연스럽게 SSR을 따로 고려하거나 Next.js같은 프레임워크를 쓰지 않아도 될 수도 있겠네요.
좋은 내용 소개 감사합니다 👍

2021-04-04 11:42 UTC, dididy approved these changes
질문은 스터디때 다 했던 것 같네요. 항상 한발 앞서 공부하시는 모습이 멋있습니다.

수고하셨습니다~!

2021-05-15 13:58 UTC, SeonHyungJo commented on React/React Server Components.md
> +우리는 Client Side의 SSR은 차선책으로 사용한다. Server에서 HTML String을 만들어서 내려준다. 만들어진 HTML은 브라우저로 가서 First Contentful Paint 또는 Largest Contentful Paint로 보인다.
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 수정되었습니다. @Dae-Hwa

2021-05-15 13:59 UTC, SeonHyungJo commented on React/React Server Components.md
> +이는 우리가 이미 알고 있는 SSR과 다른 결과물로, Client-Side의 JS bundle을 줄여주는 것이 메인이다. 아직 Production Version에는 아직 올라오지 않았지만, [RFC](https://github.com/reactjs/rfcs/blob/bf51f8755ddb38d92e23ad415fc4e3c02b95b331/text/0000
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 수정되었습니다. @jigi-kim

2021-05-15 13:59 UTC, SeonHyungJo commented on React/React Server Components.md
> +Facebook 팀에서 Server Component는를 적용해 본 결과. 번들 사이즈가 줄었다고 한다. 초기 측정 시 **-18%** 였으며, 최근에는 **-29%** 까지 되었다고 한다.
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 반영하였습니다. @jigi-kim

2021-05-15 13:59 UTC, SeonHyungJo commented on React/React Server Components.md
> +best practise 중 하나는 Code Splitting 해서 User가 필요한 코드를 필요할 때 가져올 수 있다. 기존에 우리가 사용하던 `React.lazy()`은 휴리스틱에 의존했었다.
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 반영하였습니다. @jigi-kim

2021-05-15 13:59 UTC, SeonHyungJo commented on React/React Server Components.md
> +- 메타 프레임 워크 (예 : Next.js) 외부에서 최적화는 수동으로 처리하여 `import`문을 `Dynamic import`로 대체해야 하는 경우가 많다.
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 반영하였습니다. @jigi-kim

2021-05-15 13:59 UTC, SeonHyungJo commented on React/React Server Components.md
> +Server Component는 Client Component는 모든 일반 `import`를 가능한 code-splitting 지점으로 처리하여 auto code-splitting을 해준다.
d6c13a05166f4cf106c0fdfc77a66f06a37658ac 반영하였습니다. @jigi-kim

2021-05-15 14:19 UTC, dididy approved these changes

2021-05-15 14:26 UTC, jigi-kim approved these changes

2021-05-16 16:15 UTC, Dae-Hwa approved these changes

2021-05-16 16:15 UTC, merged