Xcode
im-d-team/Dev-Docs pull request #211
Opened 2021-01-24 16:03 UTC by EUNJIHA

2021-01-28 05:50 UTC, Dae-Hwa requested changes
xcode는 새롭네요. 고생많으셨습니다.

2021-01-28 05:50 UTC, Dae-Hwa commented on iOS/Xcode.md
> +[(참고),](https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7) [(참고)](https://developer.apple.com/documentation/xcode/adding_capabilities_to_your_app)
어떤 내용인지 명시해서 링크해주면 보기에 더 좋을 것 같아요. 아래에도 마찬가지입니다. 
아니면 위에서 해주신 것처럼  제목 옆에 바로 링크를 거는 것도 방법일 수 있겠네요.

2021-01-28 05:50 UTC, Dae-Hwa commented on iOS/Xcode.md
> +### 🪴 Reference
오타가 있는 것 같네요

2021-02-25 03:02 UTC, dididy reviewed
긴 글 작성하시느라 수고 많으셨습니다! 몇가지 의문점 남겨놨어요~

2021-02-25 03:02 UTC, dididy commented on iOS/Xcode.md
> +내부 구성요소들은 executable type이나 platform에 따라서 매우 다양하기 때문에 그 때 그 때 익혀두는 것이 좋겠다.
executable type이 무엇인가요?

2021-02-25 03:02 UTC, dididy commented on iOS/Xcode.md
> +- [SwiftUI](https://developer.apple.com/documentation/swiftui)는 모든 플랫폼을 통합하여 UI를 짤 수 있다.
반응형을 염두해두고 UI를 짜야겠군요..!

2021-03-02 02:53 UTC, BKJang approved these changes
긴 글 준비하느라 고생하셨습니다.
승인할게요 👍

2021-05-11 03:52 UTC, jigi-kim approved these changes

2021-05-16 07:01 UTC, BKJang commented
담당자 실종으로 close 처리

2021-05-16 07:01 UTC, closed without merging