JUnit 설정해보기
im-d-team/Dev-Docs pull request #212
Opened 2021-02-06 21:44 UTC by Dae-Hwa

2021-05-05 11:25 UTC, dididy requested changes
JUnit에 대해 이해하는데 좋은 지침서인 것 같습니다. 수고 많으셨습니다!

2021-05-05 11:25 UTC, dididy commented on Java/junit-setup.md
> +> 상향식 하향식은 도메인 지식에 어느 정도의 이해도가 있느냐에 따라 효율성이 달라질 수 있다. 이외에도 여러 고려사항이 있겠지만, 이번에는 Junit을 사용할 때의 관점에서만 살펴봤다.
위에서 JUnit으로 표현하셨던 것 같은데 Junit을 JUnit으로 수정하면 통일성이 있어 보일 것 같습니다!

2021-05-05 11:25 UTC, dididy commented on Java/junit-setup.md
> +우선 File-Proejct Structure-Modules에 들어간다.
Project에 오타(Proejct)가 있는 것으로 보입니다.

2021-05-05 11:25 UTC, dididy commented on Java/junit-setup.md
> +대부분의 경우에서 실보다 득이 많다. 한 번도 사용해보지 않았으면 막연한 공포감이 들 수도 있지만, 위에서 살펴봤듯 아주 간단하게 적용할 수 있으니 조금씩이라도 연습해보자.
실인 상황은 어떤게 있을까요? 테스트를 작성하는 시간과 노력이 든다 정도일까요?

2021-05-08 13:19 UTC, Dae-Hwa commented on Java/junit-setup.md
> +> 상향식 하향식은 도메인 지식에 어느 정도의 이해도가 있느냐에 따라 효율성이 달라질 수 있다. 이외에도 여러 고려사항이 있겠지만, 이번에는 Junit을 사용할 때의 관점에서만 살펴봤다.
수정했습니다!

2021-05-08 13:19 UTC, Dae-Hwa commented on Java/junit-setup.md
> +우선 File-Proejct Structure-Modules에 들어간다.
수정했습니다!

2021-05-08 13:21 UTC, Dae-Hwa commented on Java/junit-setup.md
> +대부분의 경우에서 실보다 득이 많다. 한 번도 사용해보지 않았으면 막연한 공포감이 들 수도 있지만, 위에서 살펴봤듯 아주 간단하게 적용할 수 있으니 조금씩이라도 연습해보자.
네 그렇죠.
처음 써보는 것을 전제로 작성했기 때문에 글의 논지와는 조금 멀어지지만 단위 테스트나 테스트 프레임워크에 대한 이해도가 없는 사람과 협업을 하면 익숙해지기 전까지 생산성이 떨어지고 제대로 된 테스트가 작성이 되지 않을 수 있다는 점이 있겠네요.

2021-05-08 13:22 UTC, Dae-Hwa commented on Java/junit-setup.md
> +대부분의 경우에서 실보다 득이 많다. 한 번도 사용해보지 않았으면 막연한 공포감이 들 수도 있지만, 위에서 살펴봤듯 아주 간단하게 적용할 수 있으니 조금씩이라도 연습해보자.
그리고 테스트도 소스 코드이다보니 관리해야할 포인트가 늘어나는 점도 실입니다.

2021-05-10 05:43 UTC, dididy approved these changes

2021-05-11 08:41 UTC, Dae-Hwa commented on Java/junit-setup.md
> +      System.out.println("test 3 : " + someClass.someFunction(3, 3) == 6);
이렇게 안 좋다고 해석해볼 수도 있겠네요 ㅋㅋㅋ
감사합니다.

2021-05-12 00:29 UTC, jigi-kim approved these changes

2021-05-13 04:31 UTC, BKJang approved these changes
JUnit을 실제로 써보진 못했는데 Sping 공부를 계획에 두고 있는 만큼 같이 한 번 공부해봐야겠네요
고생하셨습니다 👍

2021-05-15 14:01 UTC, SeonHyungJo approved these changes
최근 토스 컨퍼런스의 테스트 커버리지 100%가 생각나네요. 

항상 테스트는 중요하게 생각하면서 좋은 글이라고 생각합니다. 👍

2021-05-15 14:02 UTC, merged