웹 보안, 웹 취약점 막기
im-d-team/Dev-Docs pull request #215
Opened 2021-03-28 15:35 UTC by SeonHyungJo

2021-04-11 13:10 UTC, Dae-Hwa reviewed
보안이나 취약점은 request만 생각했었는데 response로 취약점을 막는다는 개념을 처음 알게 됐습니다. 좋은 글 감사합니다!

2021-04-11 13:10 UTC, Dae-Hwa commented on Security/Response_Header_Security.md
> +
```suggestion
```
불필요한 띄어쓰기 인 것 같아요 !

2021-04-11 13:10 UTC, Dae-Hwa commented on Security/Response_Header_Security.md
> +```
코드블럭 타입이 json으로 설정되어 그런지, 어색하게 보이는데 혹시 저만 그런건가요?
![image](https://user-images.githubusercontent.com/24666330/114305285-818ab580-9b12-11eb-8ced-d2f04272af68.png)

2021-05-11 02:13 UTC, dididy requested changes
수고 많으셨습니다.

2021-05-11 02:13 UTC, dididy commented on Security/Response_Header_Security.md
> +```
이부분은 json말고 다른 것으로 설정하는것이 적절해 보입니다.

2021-05-11 04:17 UTC, jigi-kim commented on Security/Response_Header_Security.md
> +```
저도 동일하게 보입니다.

2021-05-11 04:17 UTC, jigi-kim approved these changes

2021-05-11 14:19 UTC, dididy commented on Security/Response_Header_Security.md
> +```
@SeonHyungJo 막상 선택하려니 뭐로할지는 모르겠네요. value에 1;mode=block처럼 quote 없이 들어가는건 json 형식이 아닌 것 같아서 말씀드려본건데 그냥 json으로 가도 될 것 같다고 생각됩니다.

2021-05-13 02:46 UTC, BKJang commented on Security/Response_Header_Security.md
> +```
js로 바꾸는게 좋겠네요

2021-05-13 02:46 UTC, BKJang approved these changes
고생하셨습니다 👍

2021-05-15 14:06 UTC, SeonHyungJo commented on Security/Response_Header_Security.md
> +아래의 사이트를 들어가서 본인의 사이트를 입력한 후 추가적인 설정 후 테스트를 누르게 되면 종합정보를 보여준다.
```suggestion
아래의 사이트를 들어가서 본인의 사이트를 입력한 후 테스트를 진행하면, 진단 후 종합테스트 결과를 보여준다.
```

로 변경하였습니다. @dididy

2021-05-15 14:07 UTC, SeonHyungJo commented on Security/Response_Header_Security.md
> +```
text로 간단하게 적용해보겠습니다!

2021-05-15 14:09 UTC, SeonHyungJo commented on Security/Response_Header_Security.md
> +```
js로 변경해서 반영하였습니다. @jigi-kim @BKJang @Dae-Hwa

2021-05-15 14:09 UTC, SeonHyungJo commented on Security/Response_Header_Security.md
> +```
@dididy

2021-05-15 14:20 UTC, dididy approved these changes
수고 많으셨습니다~

2021-05-16 16:17 UTC, Dae-Hwa approved these changes

2021-05-16 16:17 UTC, merged